"""Reviewed alternate representations for polynomial arithmetic."""


def revise(p):
    basics(p)
    sums(p)
    products(p)
    division(p)


def basics(p):
    p("polynomial-basics/kp1", 2, "A coefficient table lists powers $5,2,1$ with coefficients $6,-3,1$. State the degree and leading coefficient.")
    p("polynomial-basics/kp1", 3, "After simplifying $3x^5-2x^4+7x^3-3x^5-1$, state the degree and leading coefficient.", sketch="The two $x^5$ terms cancel. The highest remaining term is $-2x^4$, so the degree is $4$ and its coefficient is $-2$.")
    p("polynomial-basics/kp2", 1, "After combining like terms in $x^2+5x-3x+1$, classify the result as a monomial, binomial, or trinomial.", sketch="The linear terms combine to $2x$. The remaining terms $x^2$, $2x$, and $1$ give a trinomial.")
    p("polynomial-basics/kp2", 2, "An algebra-tile model contains seven positive $x^4$ pieces and no other pieces. Classify its polynomial as a monomial, binomial, or trinomial.", sketch="All seven pieces represent one like-term group, $7x^4$, so the polynomial is a monomial.")
    p("polynomial-basics/kp2", 3, "A coefficient table has nonzero entries $1,-5,6$ at powers $2,1,0$. Classify the polynomial as a monomial, binomial, or trinomial.", sketch="Each nonzero coefficient contributes a term: $x^2$, $-5x$, and $6$. Three terms give a trinomial.")
    p("polynomial-basics/kp3", 2, "An algebra-tile inventory contains five positive square tiles, three positive $x$ tiles, and seven negative unit tiles. Write its polynomial in descending powers.", sketch="The tile groups represent $5x^2$, $3x$, and $-7$; descending powers are $2,1,0$.")
    p("polynomial-basics/kp3", 3, "A coefficient list gives the constant $5$, the $x$ coefficient $2$, and two cubic contributions $-1$ and $-3$. Write the polynomial in standard form.", sketch="The cubic contributions add to $-4$; the coefficient of $x^2$ is zero. Descending order gives $-4x^3+2x+5$.")
    p("evaluating-polynomials/kp1", 1, "Use Horner form $p(x)=x(2x^2-1)$ to find $p(3)$.", sketch="Work inside out: $2(3)^2-1=17$, then $3(17)=51$.")
    p("evaluating-polynomials/kp1", 2, "Complete the output entry for input $3$ in the function table for $p(x)=x^2-5x+4$.")
    p("evaluating-polynomials/kp1", 3, "A machine maps a positive integer $x$ to $3x^2+x-1$. What output corresponds to input $4$?")
    p("evaluating-polynomials/kp2", 1, "A student obtains $14$ for $p(-3)$ when $p(x)=-x^2+5$ by squaring the minus sign with the input. Give the correct output.", sketch="Only the input is squared: $-(-3)^2+5=-9+5=-4$.")
    p("evaluating-polynomials/kp2", 2, "Complete the output entry at input $-4$ in a table for $p(x)=x(x+3)-5$.", sketch="Horner form gives $(-4)(-4+3)-5=4-5=-1$.")
    p("evaluating-polynomials/kp2", 3, "For the even polynomial $p(x)=-2x^2+3$, the table gives $p(2)=-5$. Find $p(-2)$ using symmetry.", sketch="An even power has the same value at opposite inputs. Substituting $-2$ therefore gives the stated table value, $-5$.")
    p("evaluating-polynomials/kp3", 2, answer="36")


def sums(p):
    p("adding-polynomials/kp1", 1, "Two consecutive path sections have lengths $4x-7$ and $x+2$, with $x>2$. Write their total length in standard form.")
    p("adding-polynomials/kp1", 2, "Add coefficient rows $(3,4)$ and $(2,-10)$, ordered as $(x,1)$. Write the resulting linear polynomial.")
    p("adding-polynomials/kp1", 3, "A student adds $(6x-1)+(-2x+5)$ and writes $8x+4$. Correct the polynomial.", sketch="The second $x$ coefficient is negative: $6+(-2)=4$. The constants give $-1+5=4$.")
    p("adding-polynomials/kp2", 1, "An algebra-tile tray represents $x^2-3x$ and another $2x^2+x-4$. Write the polynomial represented when the trays are combined.")
    p("adding-polynomials/kp2", 2, "Add coefficient rows $(4,-1,2)$ and $(2,3,-5)$ in columns $(x^2,x,1)$. Write the resulting polynomial.")
    p("adding-polynomials/kp2", 3, "Two garden plots have areas $x^2+5x$ and $3x^2-2x+6$ square metres, with $x>1$. Write the total area polynomial.")
    p("adding-polynomials/kp3", 1, "Add coefficient rows $(2,0,-1,0)$ and $(1,0,0,5)$ in columns $(x^3,x^2,x,1)$. Write the sum in standard form.")
    p("adding-polynomials/kp3", 2, "Two volume contributions are $x^3-4x$ and $2x^2+4x-3$, for $x>3$. Write their total as a polynomial and combine the cancelling terms.")
    p("adding-polynomials/kp3", 3, "A student adds $(3x^3+2x^2)+(x^3-2x^2+7)$ and keeps $4x^2$ in the answer. Correct the sum.")
    p("polynomial-addition-subtraction/kp1", 1, "A length $3x-8$ is cut from a bar of length $7x-2$, with $x>3$. Write the remaining length as a polynomial.")
    p("polynomial-addition-subtraction/kp1", 2, "Subtract coefficient row $(3,4,-1)$ from $(6,-2,5)$ in columns $(x^2,x,1)$. Write the resulting polynomial.")
    p("polynomial-addition-subtraction/kp1", 3, "A student writes $(4x-9)-(x-2)=3x-11$. Correct the result by distributing the subtraction sign.")
    p("polynomial-addition-subtraction/kp2", 2, "Find $P-Q$ from coefficient rows $P=(1,0,3,0)$ and $Q=(1,-2,1,-4)$ in columns $(x^3,x^2,x,1)$.")
    p("polynomial-addition-subtraction/kp2", 3, "A tile tray represents $3x^2+2x$. Removing a tray representing $x^2+2x-6$ uses zero pairs for the negative units. What polynomial remains?")
    p("polynomial-addition-subtraction/kp3", 2, "A stock model starts at $2x^2+x$, receives $x^2-5$, and dispatches $x^2-3x$, with $x>5$. Write the net stock polynomial.")
    p("polynomial-addition-subtraction/kp3", 3, "Compute $P+Q-R$ using coefficient rows $P=(1,0,-4)$, $Q=(2,1,0)$, $R=(1,-2,1)$ in columns $(x^2,x,1)$.")


def products(p):
    p("multiplying-monomials-polynomials/kp1", 1, r"Write $(-2x)(4x^3)$ as a single monomial using repeated factors $x\cdot x\cdot x\cdot x$.")
    p("multiplying-monomials-polynomials/kp1", 3, "A student multiplies $(-3x^2)(5x)$ and reports $-15x^2$. Correct the product.", sketch=r"The coefficients give $-15$; the variable factors are $x\cdot x\cdot x=x^3$.")
    p("multiplying-monomials-polynomials/kp2", 2, "A multiplication grid has row label $4x$ and column labels $3x^2,-x,2$. Add the three cell products and write the polynomial.", sketch="The cells are $12x^3$, $-4x^2$, and $8x$; they have different powers and remain separate.")
    p("multiplying-monomials-polynomials/kp2", 0, sketch="The three products are $3x(2x^2)=6x^3$, $3x(-4x)=-12x^2$, and $3x(5)=15x$.")
    p("multiplying-monomials-polynomials/kp2", 1, sketch="Multiply $2x$ by each term: $2x(x)=2x^2$ and $2x(7)=14x$.")
    p("multiplying-monomials-polynomials/kp3", 3, "Correct the expansion $-5x(x^2-3x+2)=-5x^3-15x^2-10x$.", sketch="The middle product is $(-5x)(-3x)=15x^2$; the other products are $-5x^3$ and $-10x$.")
    p("multiplying-binomials/kp1", 1, "A $2$ by $2$ product grid has row labels $x,-4$ and column labels $x,6$. Write the sum of its four cell products in standard form.")
    p("multiplying-binomials/kp1", 3, "Correct the proposed expansion $(x-5)(x+8)=x^2+13x-40$.", sketch="The cross-products are $8x$ and $-5x$, whose sum is $3x$; the constant product is $-40$.")
    p("multiplying-binomials/kp2", 1, "Use a product grid with row labels $3x,2$ and column labels $x,-5$ to write the expanded polynomial.")
    p("multiplying-binomials/kp2", 3, "Correct the proposed expansion $(2x+5)(x-3)=2x^2+2x-15$.", sketch="The cross-products are $-6x$ and $5x$, which add to $-x$, not $2x$.")
    p("multiplying-binomials/kp3", 1, "A rectangle has side lengths $2x-3$ and $2x-1$, for $x>2$. Write its area polynomial.")
    p("multiplying-binomials/kp3", 2, "A product grid uses row labels $3x,4$ and column labels $2x,-1$. Combine its four cells into a polynomial.")
    p("multiplying-binomials/kp3", 3, "Correct $(2x-5)(3x+2)=6x^2+19x-10$ by checking both cross-products.")
    p("polynomial-multiplication/kp1", 2, "A rectangular prism has one dimension $x-3$ and cross-sectional area $x^2+2x+4$, with $x>3$. Write its volume polynomial.")
    p("polynomial-multiplication/kp1", 3, "A product grid has rows $x,4$ and columns $x^2,-x,2$. Sum its six cells in standard form.")
    p("polynomial-multiplication/kp2", 2, "A box has dimensions $x+2$, $x-3$, and $x+1$, with $x>3$. Write its volume in standard form.")
    p("polynomial-multiplication/kp2", 3, "A student expands $x(x+3)(x-4)$ as $x^3-x^2-12$. Correct the product.", sketch="The binomials give $x^2-x-12$; multiplication by the outside $x$ gives $x^3-x^2-12x$.")
    p("polynomial-multiplication/kp3", 2, "A $3$ by $3$ grid has rows $x^2,-x,2$ and columns $x^2,x,-1$. Sum all nine products, including cancellations.")
    p("polynomial-multiplication/kp3", 3, "Two polynomial factors represent a rectangle's sides: $x^2+3x-2$ and $x^2-2x+1$, with $x>2$. Write its area in standard form.")


def division(p):
    p("special-products/kp1", 1, "Correct the proposed square $(x-4)^2=x^2+16$ by restoring the cross-product term.")
    p("special-products/kp2", 1, "A product grid has rows $2x,3$ and columns $2x,-3$. Use cancellation to write its total as a polynomial.")
    p("special-products/kp2", 2, "A rectangular field has sides $x+10$ and $x-10$ metres, with $x>10$. Write its area polynomial.")
    p("special-products/kp2", 3, "A student writes $(3x+1)(3x-1)=9x^2+1$. Correct the constant term and give the polynomial.")
    p("special-products/kp3", 1, "Correct $(2x+5)^2=4x^2+10x+25$ by recomputing the middle term.")
    p("binomial-cubes/kp1", 2, "A product grid has rows $x,2$ and columns $x^2,4x,4$, the terms of $(x+2)^2$. Sum all cells to expand $(x+2)^3$.")
    p("binomial-cubes/kp1", 3, "A student expands $(x+3)^3$ as $x^3+9x^2+9x+27$. Correct it by multiplying $(x+3)^2$ by $(x+3)$.", sketch="The square is $x^2+6x+9$. The linear terms in the next product are $18x+9x=27x$, giving $x^3+9x^2+27x+27$.")
    p("binomial-cubes/kp2", 3, "Correct the sign error in $(x-5)^3=x^3-15x^2-75x-125$ by multiplying $(x-5)^2$ by $(x-5)$.", sketch="The square is $x^2-10x+25$. The linear products are $50x+25x=75x$; the constant is $-125$.")
    p("binomial-cubes/kp3", 1, "A cube has side $x+4$. Use coefficients $1,3,3,1$ to write its volume polynomial.")
    p("binomial-cubes/kp3", 2, "In a binomial-cube coefficient table, substitute $a=3x$, $b=1$ into columns $a^3,3a^2b,3ab^2,b^3$. Write their sum.")
    p("binomial-cubes/kp3", 3, "Correct $(x+5)^3=x^3+15x^2+15x+125$ using the binomial-cube formula.")
    p("dividing-polynomials-by-monomials/kp1", 2, "A rectangle has area $15x^4-5x^2$ and width $5x^2$, for $x>1$. Write its length polynomial.")
    p("dividing-polynomials-by-monomials/kp1", 3, "A quotient table divides terms $6x^5$ and $-9x^3$ by $3x^2$. Combine the two quotients.")
    p("dividing-polynomials-by-monomials/kp2", 2, "Correct $(-6x^4+9x^3)/(3x^2)=-2x^2+3x^3$ by checking the exponent subtraction.")
    p("dividing-polynomials-by-monomials/kp3", 2, "For nonzero $x,y$, a product equals $15x^3y^2+10x^2y^3$ and one factor is $5x^2y$. Find the other polynomial factor.")
    p("dividing-polynomials-by-monomials/kp3", 3, "Correct $(8a^2b^3-4ab^2)/(4ab)=2ab^2-1$ by dividing the second term in both variables.")
    p("polynomial-division/kp1", 2, "Use long division to find the missing polynomial $Q$ in $x^2+x-6=(x-2)Q$.")
    p("polynomial-division/kp1", 3, "A rectangle has area $x^2-x-20$ and width $x+4$, with $x>5$. Use long division to find its length.")
    p("polynomial-division/kp2", 2, "Find $Q$ and $R$ in $x^2+5x+8=(x+2)Q+R$, where $R$ is constant, using long division.")
    p("polynomial-division/kp2", 3, "A student divides $3x^2-x+4$ by $x-1$ and proposes quotient $3x+2$ and remainder $2$. Correct the quotient-remainder result.")
    p("polynomial-division/kp3", 2, "A coefficient row for the dividend is $(1,0,0,-27)$ in descending cubic order. Divide by $x-3$ using long division and write the quotient.")
    p("polynomial-division/kp3", 3, "Use long division with zero placeholders to find $Q$ in $x^3+8=(x+2)Q$.")
    p("synthetic-division/kp1", 2, "The dividend coefficient row is $(1,-1,-6)$. Use synthetic value $3$ to find the quotient polynomial.")
    p("synthetic-division/kp1", 3, "Use synthetic division to find $Q$ in $x^3-3x^2-4x+12=(x-2)Q$.")
    p("synthetic-division/kp2", 2, "The coefficient row $(1,1,4)$ is divided using synthetic value $1$. Give the quotient polynomial and remainder.")
    p("synthetic-division/kp2", 3, "A student uses coefficient row $(2,-1,5)$ for $(2x^3-x+5)/(x-1)$. Restore the missing-power placeholder and give the correct quotient and remainder.")
    p("synthetic-division/kp3", 2, "A division identity reads $x^2+3x-1=(x-2)Q(x)+R$. Find the constant $R$ by substitution, without finding $Q$.")
    p("synthetic-division/kp3", 3, "A polynomial evaluator reports $p(1)=-3$ for $p(x)=x^3+x^2-5$. What remainder must division by $x-1$ leave?", sketch="At $x=1$, the term $(x-1)Q(x)$ vanishes, so the division identity gives $R=p(1)=-3$.")
