"""Quadratic graph and application representations."""


def revise(p):
    p("discriminant/kp1", 1, "A coefficient table gives $a=2,b=-4,c=5$. Calculate $b^2-4ac$.")
    p("discriminant/kp1", 2, "A learner uses $-36$ for $b^2$ in $x^2-6x+5=0$. Correct the discriminant.")
    p("discriminant/kp1", 3, "For the intersection equation $3x^2+5x=-1$, calculate the discriminant after moving the constant left.")
    p("discriminant/kp2", 1, "How many horizontal-axis intersection points does $y=x^2+x+1$ have? Decide from the discriminant.")
    p("discriminant/kp2", 2, "A quadratic's coefficient row is $(1,-5,2)$. Use its discriminant to give the number of distinct real zeros.")
    p("discriminant/kp2", 3, "A learner claims two real zeros for $2x^2-3x+5$ because it is quadratic. Give the actual number using the discriminant.")
    p("parabola-vertex-form/kp1", 1, "Starting with $y=x^2$, shift the graph left $2$ and down $5$, giving $y=(x+2)^2-5$. State the vertex.")
    p("parabola-vertex-form/kp1", 2, "A learner reads the vertex of $y=(x-5)^2-2$ as $(-5,-2)$. Correct the point.")
    p("parabola-vertex-form/kp1", 3, "For $y=(x+6)^2+1$, locate the point where the squared term is zero. Give the vertex as a coordinate pair.")
    p("parabola-vertex-form/kp2", 1, "Translate $y=x^2$ left $4$ and down $1$, giving $y=(x+4)^2-1$. State its opening direction and extreme $y$ value.")
    p("parabola-vertex-form/kp2", 2, "A learner calls $-4$ a maximum for $y=3(x-2)^2-4$. Give the correct opening direction and extreme value.")
    p("parabola-vertex-form/kp2", 3, "A model $y=-(x+5)^2+2$ subtracts a nonnegative square from $2$. State its opening direction and extreme value.")
    p("parabola-vertex-form/kp3", 1, "Complete the output entry at $x=1$ in a table for the vertex-form graph $y=-(x+1)^2+4$.")
    p("parabola-vertex-form/kp3", 2, "For $y=(x-1)^2+2$, a learner gives axis $x=-1$. Correct the axis and also give the ordinate at $x=3$.")
    p("parabola-vertex-form/kp3", 3, "On $y=-(x-2)^2+5$, the point $(0,1)$ is reflected across the symmetry axis. Find the $y$ value at the reflected input $x=4$.", sketch="The axis is $x=2$. Inputs $0$ and $4$ are equally far from it, so they share the ordinate $1$.")
    p("quadratic-graphs-vertex/kp1", 1, "A standard-form coefficient table gives $(a,b,c)=(1,4,1)$. Use $x=-b/(2a)$ and evaluate $y$ to find the vertex.")
    p("quadratic-graphs-vertex/kp1", 2, "A learner reports the vertex of $y=x^2-8x+10$ as $(-4,58)$. Correct the sign in $x=-b/(2a)$ and give the vertex.")
    p("quadratic-graphs-vertex/kp1", 3, "A parabolic cross-section is modelled by $y=x^2+2x-5$. Locate its lowest point using the standard-form coefficients.")
    p("quadratic-graphs-vertex/kp2", 2, "A coefficient table for a monic parabola gives $(1,-6,8)$. Find its left and right $x$-intercept points and its vertex.")
    p("quadratic-graphs-vertex/kp2", 3, "A learner gives $(0,3)$ as the $y$-intercept of $y=x^2-2x-3$. Correct that point and also find the vertex.")
    p("quadratic-graphs-vertex/kp3", 1, "A parabolic arch has signed-height model $y=-x^2+4x$. Give its opening direction, vertex, and left and right horizontal-axis intercepts.")
    p("quadratic-graphs-vertex/kp3", 2, "A parabola's coefficient row is $(1,2,-8)$. Give its opening direction, vertex, both $x$-intercept points, and its $y$-intercept point.")
    p("quadratic-graphs-vertex/kp3", 3, "A learner marks $(3,-9)$ as the vertex of $y=-x^2+6x$. Correct the graph summary: opening direction, vertex, and both $x$-intercept points.")
    p("converting-to-vertex-form/kp1", 1, "An area-square completion for $x^2-4x+7$ isolates $x^2-4x+4$ and a remainder. Write the equation $y=x^2-4x+7$ in vertex form.")
    p("converting-to-vertex-form/kp1", 2, "A learner rewrites $y=x^2+8x+10$ as $y=(x+4)^2+10$. Correct the vertex-form equation.")
    p("converting-to-vertex-form/kp1", 3, "A monic quadratic's coefficient row is $(1,-10,21)$. Write its $y$ equation in vertex form by completing the square.")
    p("converting-to-vertex-form/kp2", 1, "Rewrite the arch model $y=-x^2+2x+3$ in vertex form, extracting the leading coefficient from the $x$ terms first.")
    p("converting-to-vertex-form/kp2", 2, "A learner rewrites $y=3x^2-12x+5$ as $y=3(x-2)^2+1$. Correct the outside constant.")
    p("converting-to-vertex-form/kp2", 3, "A quadratic's coefficient row is $(-2,-8,1)$. Write its $y$ equation in vertex form, factoring the leading coefficient out of the $x$ terms.")
    p("converting-to-vertex-form/kp3", 2, "A parabolic cross-section has equation $y=x^2+12x+40$. Complete the square to express its vertex form and give the minimum height.")
    p("converting-to-vertex-form/kp3", 3, "A learner rewrites $y=2x^2+4x+5$ as $2(x+1)^2+5$. Correct the vertex-form expression and give the vertex.")
    p("quadratic-applications/kp1", 2, "A rectangle has area $45$ square units and length $4$ more than its width. A learner accepts width $-9$ from the quadratic model. Find the admissible width.", sketch="The width satisfies $w(w+4)=45$, or $(w+9)(w-5)=0$. Positive dimensions require $w=5$.")
    p("quadratic-applications/kp1", 3, "An array has $90$ cells and one more column than rows. Find the row and column counts, reported as smaller and larger.", sketch="If the row count is $n$, then $n(n+1)=90$, so $(n-9)(n+10)=0$. Counts are positive, giving $9$ rows and $10$ columns.")
    p("quadratic-applications/kp2", 2, "For the flight model $h=-5t^2+20t$ metres, a learner selects $t=0$ as the landing time. Find the positive time when the ball returns to ground level, with units.")
    p("quadratic-applications/kp2", 3, "A flight record gives $h(t)=-5t^2+40t$ metres. Locate the vertex to find the peak height, with units.")
