"""Equation-solving tasks with concrete alternate representations and corrections."""


def revise(p):
    factoring(p)
    squares(p)
    formula(p)


def factoring(p):
    p("zero-product-property/kp1", 1, "The graph $y=x(x-4)$ meets the horizontal axis where a factor vanishes. Find all corresponding $x$ values.")
    p("zero-product-property/kp1", 2, "A student keeps only $x=6$ from $(x-6)(x+2)=0$. Give the complete solution set.")
    p("zero-product-property/kp1", 3, "A rectangular model has signed area $A=x(x+9)$. Find every real parameter $x$ for which this algebraic area is zero.")
    p("zero-product-property/kp2", 1, "The graph $y=(5x+2)(x-6)$ meets the horizontal axis. Find both $x$ coordinates from the factors.")
    p("zero-product-property/kp2", 2, "A learner obtains $x=2$ or $x=-5$ from $(3x-2)(2x+5)=0$. Correct the solutions.")
    p("zero-product-property/kp2", 3, "A signed product model is $P=(4x+1)(x-3)$. Find all real parameters giving $P=0$.")
    p("zero-product-property/kp3", 1, "Find all horizontal-axis crossing values of $y=2x(x+1)(x-5)$ using the zero-product property.")
    p("zero-product-property/kp3", 2, "A student cancels $x$ in $x(x-3)(x+4)=0$ and loses a root. Give the complete solution set.")
    p("zero-product-property/kp3", 3, "The signed volume model $V=3x(x+1)(x-6)$ vanishes. Find every real parameter value that makes any variable factor zero.")
    p("quadratic-equations-factoring/kp1", 1, "Find all horizontal-axis crossing values of $y=x^2-5x-14$ by factoring its quadratic.")
    p("quadratic-equations-factoring/kp1", 2, "A learner proposes roots $-4$ and $9$ for $x^2+5x-36=0$. Correct both roots by factoring.")
    p("quadratic-equations-factoring/kp1", 3, "A quadratic's coefficient row is $(1,9,18)$ in descending order. Set the polynomial equal to zero and solve by factoring.")
    p("quadratic-equations-factoring/kp2", 1, "Find the $x$ coordinates where the curves $y=3x^2$ and $y=12x$ intersect. Rearrange and solve by factoring.")
    p("quadratic-equations-factoring/kp2", 2, "A learner rearranges $x^2+4x=21$ as $x^2+4x+21=0$. Correct the rearrangement and give all roots by factoring.")
    p("quadratic-equations-factoring/kp2", 3, "A signed-area model equates $5x^2$ and $20x$. Move the terms to one side and find every real solution, including zero.")
    p("quadratic-equations-factoring/kp3", 1, "Find the horizontal-axis crossing values of $y=x^2-25$ by factoring a difference of squares.")
    p("quadratic-equations-factoring/kp3", 2, "A learner factors $3x^2+5x-2$ as $(3x-1)(x+2)$ but reports $x=1,-2$. Correct the solution set.")
    p("quadratic-equations-factoring/kp3", 3, "A quadratic's coefficient row is $(1,0,-64)$. Set it equal to zero and solve by factoring the special pattern.")
    p("writing-quadratics-from-roots/kp1", 1, "A monic parabola crosses the horizontal axis at $(2,0)$ and $(4,0)$. Write its zero equation in expanded standard form.")
    p("writing-quadratics-from-roots/kp1", 2, "A learner uses $(x+5)(x-2)=0$ for roots $5,-2$. Correct the signs and write the monic equation in expanded standard form.")
    p("writing-quadratics-from-roots/kp1", 3, "A root table contains $-4$ and $-7$, each once. Build and expand the monic quadratic equation.")
    p("writing-quadratics-from-roots/kp2", 1, "A monic parabola crosses the horizontal axis at the origin and at $(-6,0)$. Write its quadratic zero equation.")
    p("writing-quadratics-from-roots/kp2", 2, "A learner writes $x^2-9=0$ for a quadratic whose only root is $-3$. Write the correct monic quadratic equation.")
    p("writing-quadratics-from-roots/kp2", 3, "A factor record says one root is zero and the other is $5$. Build and expand the monic quadratic zero equation.")
    p("writing-quadratics-from-roots/kp3", 1, "A parabola has horizontal-axis intercepts $(2/3,0)$ and $(1,0)$. Write its quadratic zero equation with the smallest positive integer leading coefficient.")
    p("writing-quadratics-from-roots/kp3", 2, "A learner chooses $x-4$ for the root $1/4$ and $x+2$ for the root $-2$. Correct the first factor and expand a quadratic zero equation with integer coefficients.")
    p("writing-quadratics-from-roots/kp3", 3, "A root table lists $3/5$ and $1$. Clear the denominator in the linear factor for the fractional root and write the expanded quadratic zero equation.")


def squares(p):
    p("square-root-property/kp1", 1, "The graph $y=x^2$ intersects the horizontal line $y=100$. Find both $x$ coordinates using square roots.")
    p("square-root-property/kp1", 2, "A student concludes $x=9$ from $x^2=81$. Give the complete real solution set.")
    p("square-root-property/kp1", 3, "On a number line, the squared distance of $x$ from zero is $144$. Find all signed coordinates $x$.", sketch=r"Distance is $\sqrt{144}=12$, so the two coordinates are $12$ and $-12$.")
    p("square-root-property/kp2", 0, "Solve $3(x-1)^2-27=0$ by first isolating the square.", "x = 4 or x = -2", "Divide by $3$ after adding $27$: $(x-1)^2=9$. Thus $x-1=3$ or $x-1=-3$, giving $4$ and $-2$.")
    p("square-root-property/kp2", 1, "The parabola $y=(x-3)^2$ meets the line $y=16$. Find both $x$ coordinates using the square-root property.")
    p("square-root-property/kp2", 2, "Correct a learner's single solution $x=6$ for $2(x-2)^2-32=0$. Give all real solutions.", "x = 6 or x = -2", r"Isolate $(x-2)^2=16$, then use both signs: $x-2=\pm4$. The roots are $6$ and $-2$.")
    p("square-root-property/kp2", 3, "A number-line coordinate has squared distance $25$ from $-2$. Find all coordinates using $(x+2)^2=25$.")
    p("square-root-property/kp3", 1, "Find the $x$ coordinates where $y=(x+1)^2$ meets $y=5$. Keep both answers exact.")
    p("square-root-property/kp3", 2, r"A student writes $x=\pm10$ for $x^2=20$. Give the corrected real solutions with simplified radicals.")
    p("square-root-property/kp3", 3, "A coordinate has squared distance $8$ from $2$ on a number line. Find all such coordinates in exact radical form.")
    p("completing-the-square/kp1", 1, "An area layout contains $x^2$ with two signed strips totalling $-6x$. State the missing corner constant and the completed squared binomial.")
    p("completing-the-square/kp1", 2, "A learner adds $10$ to $x^2+10x$ and claims a perfect square. Give the correct added constant and squared-binomial form.")
    p("completing-the-square/kp1", 3, r"Fill the missing constant in $x^2-4x+\square$ so that it is a perfect square. Report both the constant and the squared binomial.")
    p("completing-the-square/kp2", 1, "Find the horizontal-axis crossing values of $y=x^2-4x-12$ by completing the square.")
    p("completing-the-square/kp2", 2, "A learner changes $x^2+8x+7=0$ into $(x+4)^2=-7$. Repair the square-completion step and give all roots.", sketch=r"Move $7$, then add $16$ to both sides: $(x+4)^2=9$. Thus $x=-4\pm3$, giving $-1,-7$.")
    p("completing-the-square/kp2", 3, "A monic quadratic has coefficient row $(1,-10,16)$. Set it equal to zero and solve by completing the square.")
    p("completing-the-square/kp3", 1, "Find the horizontal-axis crossing values of $y=x^2-8x+5$ by completing the square. Keep exact radicals.")
    p("completing-the-square/kp3", 2, "A learner rewrites $x^2+4x-1=0$ as $(x+2)^2=1$. Correct the completed square and give both exact roots.")
    p("completing-the-square/kp3", 3, "A monic quadratic's coefficient row is $(1,-2,-6)$. Set it equal to zero and complete the square to find both exact roots.")
    p("completing-square-leading-coefficient/kp1", 1, "Find the horizontal-axis crossing values of $y=3x^2-6x-9$ by dividing through by the leading coefficient and completing the square.")
    p("completing-square-leading-coefficient/kp1", 2, "A learner divides $2x^2-4x-6=0$ by $2$ but keeps the constant $-6$. Correct this and finish solving by completing the square.")
    p("completing-square-leading-coefficient/kp1", 3, "A quadratic has coefficient row $(3,9,-30)$. Set it equal to zero, divide by its leading coefficient, and complete the square to find both roots.")
    p("completing-square-leading-coefficient/kp2", 1, "Find the horizontal-axis crossing values of $y=2x^2+6x+1$ by completing the square after division. Keep exact fractions and radicals.")
    p("completing-square-leading-coefficient/kp2", 2, "A learner gets $x^2-4x-5=0$ after dividing $2x^2-8x-5=0$ by $2$. Correct the constant and solve by completing the square.")
    p("completing-square-leading-coefficient/kp2", 3, "A quadratic has coefficient row $(2,10,1)$. Set it equal to zero, divide by $2$, and complete the square. Give exact roots.")
    p("completing-square-leading-coefficient/kp3", 1, "Find the horizontal-axis crossing values of $y=x^2-x-1$ by completing the square with a fractional half-coefficient.")
    p("completing-square-leading-coefficient/kp3", 2, "A learner adds $49$ to complete the square for $x^2+7x+2=0$. Correct the added amount and solve exactly by completing the square.")
    p("completing-square-leading-coefficient/kp3", 3, "A monic quadratic has coefficient row $(1,-3,-3)$. Set it equal to zero and complete the square using the exact half of the middle coefficient.")


def formula(p):
    p("applying-the-quadratic-formula/kp1", 2, "A coefficient table lists powers $2,1,0$ with entries $4,3,-1$. State $a,b,c$ for the quadratic formula.")
    p("applying-the-quadratic-formula/kp1", 3, "A learner identifies $b=3$ from $x^2+5=3x$. Move all terms to the left and state the correct $a,b,c$.")
    p("applying-the-quadratic-formula/kp2", 1, "Find the horizontal-axis crossing values of $y=2x^2-7x+3$ using the quadratic formula.")
    p("applying-the-quadratic-formula/kp2", 2, "A learner uses $-2$ in place of $-b$ for $x^2-2x-8=0$. Correct the formula substitution and give both roots.")
    p("applying-the-quadratic-formula/kp2", 3, "A quadratic has coefficient row $(3,-5,2)$. Set it equal to zero and find both roots using the quadratic formula.")
    p("applying-the-quadratic-formula/kp3", 1, "Find the horizontal-axis crossing values of $y=4x^2-4x-3$ using the quadratic formula; reduce both fractions.")
    p("applying-the-quadratic-formula/kp3", 2, "A learner uses denominator $4$ in the formula for $4x^2+11x-3=0$. Correct the denominator and solve with reduced fractions.")
    p("applying-the-quadratic-formula/kp3", 3, "A quadratic has coefficient row $(9,-6,-8)$. Set it equal to zero and use the quadratic formula, reducing both roots fully.")
    p("quadratic-formula/kp1", 1, "Find the horizontal-axis crossing values of $y=x^2+6x+4$ with the quadratic formula. Simplify the discriminant's radical.")
    p("quadratic-formula/kp1", 2, r"A learner obtains $(2\pm\sqrt{12})/2$ from $x^2-2x-2=0$. Finish simplifying and give both roots separately.")
    p("quadratic-formula/kp1", 3, "A quadratic has coefficient row $(1,8,13)$. Set it equal to zero, use the quadratic formula, and simplify the radical and fraction.")
    p("quadratic-formula/kp2", 1, "Find the horizontal-axis crossing values of $y=3x^2-2x-2$ using the quadratic formula. Cancel the common numerator-denominator factor.")
    p("quadratic-formula/kp2", 2, r"A learner stops at $(2\pm\sqrt{44})/4$ for $2x^2-2x-5=0$. Give both roots in fully reduced radical form.")
    p("quadratic-formula/kp2", 3, "A quadratic has coefficient row $(3,4,-2)$. Set it equal to zero and use the quadratic formula, reducing the final fractions.")
    p("quadratic-formula/kp3", 2, r"A learner stops at $(-4\pm\sqrt{24})/4$ for $2x^2+4x-1=0$. Give both fully reduced exact roots.")
    p("quadratic-formula/kp3", 3, "A learner replaces the negative discriminant of $x^2+4x+8=0$ with its absolute value. How many real roots does the actual quadratic have?", sketch="The discriminant is $4^2-4(1)(8)=-16$. A negative discriminant has no real square root, so the real-root count is $0$.")
