"""Constructed factors, with expanded coefficients shown to the learner."""


def build(a):
    gcf(a)
    quadratics(a)
    patterns(a)
    advanced(a)


def gcf(a):
    a("gcf-of-monomials/kp1", "Find the greatest common factor of ${a}$ and $36$.", "gcd(a,36)", r"Factor ${a}$ and $36=2^2\cdot3^2$ into primes. Multiply only common primes, each to the lower exponent.", "A common factor must divide both coefficients exactly.", axes={"a":range(12,36,2)})
    a("gcf-of-monomials/kp2", "Find the GCF monomial of ${a}x^4$ and $12x^2$.", "gcd(a,12)*x**2", r"The coefficient GCF is $\gcd({a},12)$. The lower shared exponent of $x$ is $2$, so multiply that coefficient by $x^2$.", "Separate the integer GCF from the minimum shared exponent.")
    a("gcf-of-monomials/kp3", "Find the GCF of ${a}x^3y^2$, $12x^2y^4$, and $18xy^3$.", "gcd(gcd(a,12),18)*x*y**2", r"The coefficient GCF is $\gcd({a},12,18)$. The minimum exponents are $1$ for $x$ and $2$ for $y$.", "Use the lowest exponent that occurs in every monomial.")
    a("factoring-gcf/kp1", "Extract the greatest common monomial factor from ${a}x^2+{b}x$.", "a*x*(x+3)", "The coefficient GCF is ${a}$ because ${b}=3({a})$. The common variable factor is $x$; the two quotients are $x$ and $3$.", "Divide each term by the common monomial to form the remaining bracket.", derived={"b":"3*a"})
    a("factoring-gcf/kp2", "Factor $-{a}x^4-{b}x^2$ by extracting a negative GCF.", "-a*x**2*(x**2+3)", "Extract $-{a}x^2$: the first term leaves $x^2$ and the second leaves $3$. Both remaining coefficients are positive.", "Choose the negative common factor, including the lowest variable power.", derived={"b":"3*a"})
    a("factoring-gcf/kp3", "Factor $2x(x+{a})+3(x+{a})$ without expanding the repeated binomial.", "(x+a)*(2*x+3)", "Both terms contain $x+{a}$. The remaining factors are $2x$ and $3$, whose sum forms the other bracket.", "Treat the repeated binomial as one common factor.")
    a("factoring-by-grouping/kp1", "Factor $x^3+{a}x^2+2x+{b}$ by grouping the first two and last two terms.", "(x+a)*(x**2+2)", "The groups become $x^2(x+{a})$ and $2(x+{a})$. Extract their shared binomial; $x^2+2$ is irreducible over the integers.", "Factor a GCF from each pair and compare the remaining brackets.", derived={"b":"2*a"})
    a("factoring-by-grouping/kp2", "Factor $2x^3+{a}x^2+6x+{b}$ by grouping.", "(2*x+a)*(x**2+3)", "The groups are $x^2(2x+{a})$ and $3(2x+{a})$. Extract the shared binomial $2x+{a}$.", "Both groups must leave the same binomial factor.", axes={"a":range(1,25,2)}, derived={"b":"3*a"})


def quadratics(a):
    a("factoring-monic-trinomials/kp1", "Factor $x^2+{a}x+{b}$ into two integer monic binomials.", "(x+2)*(x+a-2)", "The constants $2$ and ${a}-2$ add to ${a}$ and multiply to ${b}$. Use them as the constants in the two binomials.", "Find two positive integers with the required product and sum.", axes={"a":[5,6,7,9,10,11,12,13,14,15,16,17]}, derived={"b":"2*a-4"})
    a("factoring-monic-trinomials/kp2", "Factor $x^2+{a}x-{b}$ into integer binomials.", "(x-2)*(x+a+2)", "The constants $-2$ and ${a}+2$ have sum ${a}$ and product $-{b}$. Their opposite signs match the negative constant.", "The two constant factors have opposite signs.", derived={"b":"2*a+4"})
    a("factoring-monic-trinomials/kp3", "Factor $x^2-{a}x+{b}$ into integer binomials.", "(x-2)*(x-a+2)", "Use constants $-2$ and $-({a}-2)$: their sum is $-{a}$ and product is ${b}$.", "A positive product and negative sum require two negative constants.", axes={"a":[6,7,8,10,11,12,13,14,15,16,17,18]}, derived={"b":"2*a-4"})
    a("factoring-trinomials/kp1", "Factor $2x^2+{a}x+{b}$ using the $ac$ method.", "(2*x+1)*(x+(a-1)/2)", "Here $2c={a}-1$. Split the middle term into $({a}-1)x+x$, group, and extract the repeated binomial.", "The split coefficients must multiply to the leading coefficient times the constant.", axes={"a":[5,9,11,13,15,17,19,21,23,25,27,29]}, derived={"b":"(a-1)/2"})
    a("factoring-trinomials/kp2", "Factor $2x^2+{a}x-{b}$ using the $ac$ method.", "(2*x-1)*(x+(a+1)/2)", "Since $2c=-({a}+1)$, split the middle term as $({a}+1)x-x$. Grouping then exposes $2x-1$.", "Use opposite signs in the split pair because the constant is negative.", axes={"a":range(3,27,2)}, derived={"b":"(a+1)/2"})
    a("factoring-trinomials/kp3", "Factor $2x^2+{a}x+{b}$ completely, extracting the GCF first.", "2*(x+1)*(x+a/2-1)", "Extract $2$, leaving $x^2+({a}/2)x+{b}/2$. Its constant factors $1$ and ${a}/2-1$ have the required sum.", "Remove the integer common factor before factoring the trinomial.", axes={"a":[6,8,10,14,16,18,20,22,24,26,28,30]}, derived={"b":"a-2"})


def patterns(a):
    a("difference-of-squares/kp1", "Factor $x^2-{a}$ over the integers using a difference of squares.", "(x-sqrt(a))*(x+sqrt(a))", r"The square roots of the two terms are $x$ and $\sqrt{{{a}}}$. Opposite-sign binomials cancel their cross-products.", "Use conjugate binomial factors.", axes={"a":[n*n for n in range(1,11)]})
    a("difference-of-squares/kp2", "Factor $4x^4-{a}$ over the integers using a difference of squares.", "(2*x**2-sqrt(a))*(2*x**2+sqrt(a))", r"The two squares are $(2x^2)^2$ and $(\sqrt{{{a}}})^2$. Their conjugates are the integer factors.", "Take the square root of the coefficient and halve the even exponent.", axes={"a":[n*n for n in range(1,25,2)]})
    a("difference-of-squares/kp3", "Factor $3x^2-{a}$ completely over the integers.", "3*(x-sqrt(a/3))*(x+sqrt(a/3))", "Extract $3$, leaving $x^2-{a}/3$. The remaining constant is a perfect square, so factor the conjugate pair.", "First remove the common coefficient, then inspect the remaining two terms.", axes={"a":[3*n*n for n in [2,4,5,6,7,8,9,10,11,12,13,14]]})
    a("perfect-square-trinomials/kp1", "The end terms of $x^2+{a}x+{b}$ are squares. Verify the middle-term condition and write the polynomial as one squared binomial.", "(x+a/2)**2", "The constant's square root is ${a}/2$. Twice its product with $x$ is ${a}x$, so the middle term confirms the square pattern.", "Check twice the product of the end terms' square roots.", axes={"a":[4,10,12,14,16,18,20,22,24,26,28,30]}, derived={"b":"a**2/4"})
    a("perfect-square-trinomials/kp2", "Factor $x^2-{a}x+{b}$ as a squared monic binomial.", "(x-a/2)**2", "The constant is $({a}/2)^2$, and the middle term is $-2({a}/2)x$. Thus the binomial uses subtraction.", "The middle term determines the sign inside the squared binomial.", axes={"a":[4,6,8,10,14,18,20,22,24,26,28,30]}, derived={"b":"a**2/4"})
    a("perfect-square-trinomials/kp3", "Factor $4x^2+{a}x+{b}$ as a squared binomial.", "(2*x+a/4)**2", "The first square root is $2x$ and the second is ${a}/4$. Twice their product is ${a}x$, confirming the pattern.", "Check both squared end terms and the cross-product.", axes={"a":range(8,56,4)}, derived={"b":"a**2/16"})
    a("sum-difference-of-cubes/kp1", "Factor $x^3-{a}$ using the difference-of-cubes identity.", "(x-a**(1/3))*(x**2+a**(1/3)*x+a**(2/3))", r"Let $b=\sqrt[3]{{{a}}}$. The factors are $x-b$ and $x^2+bx+b^2$; the inner cross-products cancel when multiplied.", "The quadratic factor in a difference of cubes uses positive signs.", axes={"a":[n**3 for n in range(6,18)]})
    a("sum-difference-of-cubes/kp2", "Factor $x^3+{a}$ using the sum-of-cubes identity.", "(x+a**(1/3))*(x**2-a**(1/3)*x+a**(2/3))", r"Let $b=\sqrt[3]{{{a}}}$. Use $x+b$ and $x^2-bx+b^2$; the quadratic middle sign opposes the linear sign.", "For a cube sum, the trinomial middle sign is negative.", axes={"a":[n**3 for n in range(6,18)]})
    a("sum-difference-of-cubes/kp3", "Factor $8x^3+{a}$ over the integers using the cube identity.", "(2*x+a**(1/3))*(4*x**2-2*a**(1/3)*x+a**(2/3))", r"The cube roots are $2x$ and $\sqrt[3]{{{a}}}$. Square the first root, subtract their product, and add the square of the second for the quadratic factor.", "Take cube roots of the full terms, including their coefficients.", axes={"a":[n**3 for n in range(1,25,2)]})


def advanced(a):
    a("quadratics-in-form/kp1", "Factor $x^4+{a}x^2+{b}$ over the integers using a middle-power substitution.", "(x**2+2)*(x**2+a-2)", "Set $u=x^2$. The quadratic becomes $u^2+{a}u+{b}=(u+2)(u+{a}-2)$. Replace $u$ by $x^2$; both quadratics have positive constants.", "Treat the middle power as a new unknown before factoring.", axes={"a":range(7,19)}, derived={"b":"2*a-4"})
    a("quadratics-in-form/kp2", "Factor $x^4-{a}x^2+{b}$ completely over the integers.", "(x-1)*(x+1)*(x-sqrt(b))*(x+sqrt(b))", "Set $u=x^2$. Since ${a}={b}+1$, the quadratic factors as $(u-1)(u-{b})$. Return to $x$ and split both differences of squares.", "After substitution, inspect every quadratic factor for another square difference.", axes={"a":[n*n+1 for n in [3,5,6,7,8,9,10,11,12,13,14,15]]}, derived={"b":"a-1"})
    a("quadratics-in-form/kp3", "Factor $2x^4+{a}x^2+{b}$ over the integers using quadratic form.", "(2*x**2+1)*(x**2+(a-1)/2)", "Set $u=x^2$ and split the middle term as $({a}-1)u+u$. Group to get $(2u+1)(u+({a}-1)/2)$, then substitute back.", "Use the non-monic trinomial method on the substituted unknown.", axes={"a":range(7,31,2)}, derived={"b":"(a-1)/2"})
    a("choosing-factoring-strategy/kp1", "For $3x^2-{a}$, choose the first factoring move: GCF, difference of squares, or trinomial factoring.", "GCF", "Both coefficients share $3$. Extract that common factor before considering the two-term pattern inside.", "Check for a common factor before selecting a pattern.", axes={"a":range(6,42,3)}, contract={"kind":"label","options":[["GCF"],["difference of squares"],["trinomial factoring"]]})
    a("choosing-factoring-strategy/kp2", "Factor $2x^3-{a}x$ completely over the integers.", "2*x*(x-sqrt(a/2))*(x+sqrt(a/2))", "Extract $2x$, leaving $x^2-{a}/2$. Its constant is a square, so split the remaining difference of squares.", "Remove a common monomial, then inspect the two-term remainder.", axes={"a":[2*n*n for n in range(3,15)]})
    a("choosing-factoring-strategy/kp3", "Factor $x^4-{a}$ completely over the integers.", "(x-a**(1/4))*(x+a**(1/4))*(x**2+sqrt(a))", r"First write $(x^2-\sqrt{{{a}}})(x^2+\sqrt{{{a}}})$. The first factor is another difference of squares; the second remains irreducible over the integers.", "Continue factoring a factor whenever it still matches a square-difference pattern.", axes={"a":[n**4 for n in range(4,16)]})
