"""Vertex, discriminant, and modelling templates with explicit response order."""


def build(a):
    a("discriminant/kp1", "Calculate the discriminant for ${a}x^2+({b})x+2=0$.", "b**2-8*a", "Read $a={a}$, $b={b}$, and $c=2$. Then $b^2-4ac=({b})^2-8({a})$, keeping the square nonnegative.", "Square the signed linear coefficient before subtracting the coefficient product.", axes={"a":range(1,4),"b":range(-2,2)})
    a("discriminant/kp2", "Use the discriminant to count the distinct real roots of $x^2+{a}x+{b}=0$.", "1+(a**2-4*b)/max(1,abs(a**2-4*b))", "Compute $D=({a})^2-4({b})$. A positive $D$ gives two distinct real roots, zero gives one, and negative gives none.", "The sign of the discriminant determines the count.", axes={"a":[2,4,6],"b":range(1,5)})
    a("parabola-vertex-form/kp1", "Read the vertex of $y=2(x-({a}))^2-3$ as a coordinate pair.", "(a,-3)", "The squared term is zero at $x={a}$. At that input $y=-3$, so these values are the vertex coordinates.", "Set the expression inside the square equal to zero.", axes={"a":list(range(-6,0))+list(range(1,7))})
    a("parabola-vertex-form/kp2", "For $y=2(x-1)^2+{a}$, report (opening direction, extreme value), using upward or downward for direction.", "(upward,a)", "The coefficient of the square is positive, so the graph opens upward. The square reaches zero at $x=1$, leaving the minimum value ${a}$.", "Use the sign of the square's coefficient and the vertical shift.")
    a("parabola-vertex-form/kp3", "For $y=(x-{a})^2-3$, report (axis coordinate, y at x=0), where the axis is x equal to the first entry.", "(a,a**2-3)", "The axis passes through $x={a}$. Substitution of zero gives $y=(0-{a})^2-3=({a})^2-3$.", "Read the axis from the vertex form, then substitute the requested input.")
    a("quadratic-graphs-vertex/kp1", "Find the vertex of $y=x^2+{a}x+3$ using the standard-form coefficients.", "(-a/2,3-a**2/4)", "The vertex input is $x=-{a}/2$. Substitute it into the quadratic and combine the two squared-coefficient terms; the output simplifies to $3-({a})^2/4$.", "Use the negative linear coefficient divided by twice the leading coefficient, then evaluate the output.", axes={"a":range(2,26,2)})
    a("quadratic-graphs-vertex/kp2", "For $y=x^2-{a}x+{b}$, report (left x-intercept point, right x-intercept point, vertex point).", "((1,0),(a-1,0),(a/2,b-a**2/4))", "Factor as $(x-1)(x-({a}-1))$ for the intercepts. Their midpoint is $x={a}/2$; evaluation there gives $y={b}-({a})^2/4$.", "Find the zeros, then evaluate the quadratic halfway between them.", axes={"a":range(4,16)}, derived={"b":"a-1"})
    a("quadratic-graphs-vertex/kp3", "For $y=x^2-{a}x+{b}$, report (opening direction, vertex, left x-intercept, right x-intercept, y-intercept), using upward or downward for direction.", "(upward,(a/2,b-a**2/4),(1,0),(a-1,0),(0,b))", "The leading coefficient is positive. Factoring as $(x-1)(x-({a}-1))$ gives both zeros; evaluate the midpoint for the vertex and zero input for the vertical intercept.", "Combine the leading coefficient, the zeros, and the symmetry axis.", axes={"a":range(4,16)}, derived={"b":"a-1"})
    a("converting-to-vertex-form/kp1", "Convert $y=x^2+{a}x+3$ to vertex form. Return the expression on the right of y equals.", "(x+a/2)**2+3-a**2/4", "Add and subtract $({a}/2)^2$: the square is $(x+{a}/2)^2$ and the remaining constant is $3-({a}/2)^2$.", "Complete the square while keeping the polynomial's value unchanged.", axes={"a":range(2,26,2)})
    a("converting-to-vertex-form/kp2", "Convert $y=2x^2+{a}x+3$ to vertex form. Return the expression on the right of y equals.", "2*(x+a/4)**2+3-a**2/8", "Factor $2$ from the variable terms, then complete the inner square with half-coefficient ${a}/4$. Compensate outside by subtracting $2({a}/4)^2$.", "The leading coefficient multiplies the square-completion adjustment too.", axes={"a":range(4,52,4)})
    a("converting-to-vertex-form/kp3", "For $y=x^2+{a}x+3$, report (vertex-form expression, minimum value) after completing the square.", "((x+a/2)**2+3-a**2/4,3-a**2/4)", "Complete the square to $(x+{a}/2)^2+3-({a}/2)^2$. The square has minimum zero, leaving the outside constant as the minimum value.", "Once the square is isolated, read the lowest output from the remaining constant.", axes={"a":range(2,26,2)})
    a("quadratic-applications/kp1", "A rectangle has length three units more than its width and area ${a}$ square units. Find its positive width.", "(-3+sqrt(9+4*a))/2", "Let width be $w$. The area equation $w(w+3)={a}$ becomes $w^2+3w-{a}=0$. Factor using the integer pair with product $-{a}$ and sum $3$; retain the positive root for a length.", "Build the area equation from width times length and discard a negative length.", axes={"a":[n*(n+3) for n in range(2,14)]})
    a("quadratic-applications/kp2", "A ball's height is $h(t)=-5t^2+{a}t$ metres. Find the maximum height, including units.", "a**2/20", "The vertex time is $t={a}/10$. Substitution gives $-5({a}/10)^2+{a}({a}/10)=({a})^2/20$ metres.", "The negative quadratic coefficient makes the vertex the highest point.", axes={"a":range(10,130,10)}, unit="m")
