"""Exact solution pairs; tuple order is explicit in each learner prompt."""


def build(a):
    factoring(a)
    square_roots(a)
    completion(a)
    formula(a)


def factoring(a):
    a("zero-product-property/kp1", "Solve $(x-{a})(x+3)=0$. Report the roots as (smaller, larger).", "(-3,a)", "A product vanishes when a factor does: $x-{a}=0$ gives ${a}$, and $x+3=0$ gives $-3$. Order the two roots.", "Set each variable factor equal to zero.")
    a("zero-product-property/kp2", "Solve $(2x-{a})(3x+1)=0$. Report the roots as (smaller, larger).", "(-1/3,a/2)", "The factors give $2x={a}$ and $3x=-1$. Divide by their coefficients, then order the roots.", "A coefficient in a linear factor must be divided out when solving.")
    a("zero-product-property/kp3", "Solve $x(x-{a})(x+2)=0$. Report all roots in increasing order as a tuple.", "(-2,0,a)", "The three variable factors vanish at $0$, ${a}$, and $-2$. The constant-free factor $x$ contributes the zero root.", "Keep the root from every variable factor, including the outside monomial.")
    a("quadratic-equations-factoring/kp1", "Solve $x^2+{a}x+{b}=0$ by factoring. Report the roots as (smaller, larger).", "(2-a,-2)", "The constants $2$ and ${a}-2$ give product ${b}$ and sum ${a}$, so $(x+2)(x+{a}-2)=0$. Set each factor to zero.", "Factor the trinomial before using the zero-product property.", axes={"a":range(5,17)}, derived={"b":"2*a-4"})
    a("quadratic-equations-factoring/kp2", "Solve $x^2+{a}x={b}$ by rearranging and factoring. Report the roots as (smaller, larger).", "(-a-2,2)", "Moving ${b}$ left gives $x^2+{a}x-{b}=0=(x-2)(x+{a}+2)$. The two factors give the roots.", "Put zero on one side before applying the zero-product property.", derived={"b":"2*a+4"})
    a("quadratic-equations-factoring/kp3", "Solve $2x^2+{a}x-{b}=0$ by factoring. Report the roots as (smaller, larger).", "(-(a+1)/2,1/2)", "Split the middle term as $({a}+1)x-x$ and group to get $(2x-1)(x+({a}+1)/2)=0$. Solve both factors.", "Use the non-monic trinomial's leading coefficient in the factorization.", axes={"a":range(3,27,2)}, derived={"b":"(a+1)/2"})
    a("writing-quadratics-from-roots/kp1", "A monic quadratic equation has roots ${a}$ and $-3$. Write its expanded left side $P(x)$ for the equation $P(x)=0$.", "x**2+(3-a)*x-3*a", "Use factors $x-{a}$ and $x+3$. Their product expands to $x^2+(3-{a})x-3({a})$.", "Build one linear factor from each root, then multiply.")
    a("writing-quadratics-from-roots/kp2", "A monic quadratic has the repeated root ${a}$. Write its expanded left side $P(x)$ for $P(x)=0$.", "x**2-2*a*x+a**2", "The repeated root gives two equal factors: $(x-{a})^2$. Expansion includes the cross term $-2({a})x$.", "A repeated root appears in both linear factors.")
    a("writing-quadratics-from-roots/kp3", "A quadratic has roots $1/{a}$ and $-2$. With smallest positive integer leading coefficient, write its expanded left side $P(x)$ for $P(x)=0$.", "a*x**2+(2*a-1)*x-2", "Clear the first factor's denominator to get ${a}x-1$. Multiply it by $x+2$, producing integer coefficients with no common factor.", "Turn the fractional root into an integer-coefficient linear factor.")


def square_roots(a):
    a("square-root-property/kp1", "Solve $x^2={a}$ using the square-root property. Report the roots as (smaller, larger).", "(-sqrt(a),sqrt(a))", r"Taking square roots gives $x=\pm\sqrt{{{a}}}$. Both signs are needed because squaring either produces ${a}$.", "A positive square has two real square roots with opposite signs.", axes={"a":[n*n for n in [2,3,4,5,6,8,11,13,14,15,16,17]]})
    a("square-root-property/kp2", "Solve $2(x-3)^2-{a}=0$ by isolating the square. Report the roots as (smaller, larger).", "(3-sqrt(a/2),3+sqrt(a/2))", "Move the constant and divide by $2$: $(x-3)^2={a}/2$. Take both square-root signs and add the shift $3$.", "Isolate the entire shifted square before taking roots.", axes={"a":[2*n*n for n in [2,3,5,6,7,8,9,10,11,12,13,14]]})
    a("square-root-property/kp3", "Solve $x^2={a}$ with simplified exact radicals. Report the roots as (smaller, larger).", "(-sqrt(a/2)*sqrt(2),sqrt(a/2)*sqrt(2))", r"Write ${a}$ as a perfect square times $2$, extract the square factor from $\sqrt{{{a}}}$, and retain both signs.", "Separate a square factor inside the radical before writing both roots.", axes={"a":[2*n*n for n in range(2,14)]})


def completion(a):
    a("completing-the-square/kp1", "Complete the square for $x^2+{a}x$. Report (added constant, squared binomial) in that order.", "(a**2/4,(x+a/2)**2)", "Half the linear coefficient is ${a}/2$. Squaring that half gives the added constant, and $x+{a}/2$ is the binomial to square.", "The required constant is the square of half the linear coefficient.", axes={"a":range(4,28,2)})
    a("completing-the-square/kp2", "Solve $x^2+6x-{a}=0$ by completing the square. Report the roots as (smaller, larger).", "(-3-sqrt(a+9),-3+sqrt(a+9))", "Move ${a}$ to the right and add $9$: $(x+3)^2={a}+9$. Take both square-root signs, then subtract $3$.", "Add the same square-completion constant to both sides.", axes={"a":[n*n-9 for n in range(4,16)]})
    a("completing-the-square/kp3", "Solve $x^2+4x-{a}=0$ by completing the square. Give exact roots as (smaller, larger).", "(-2-sqrt(a+4),-2+sqrt(a+4))", "Move ${a}$ and add $4$ to both sides: $(x+2)^2={a}+4$. The right side is not a square, so keep its exact radical and subtract $2$.", "Keep a nonsquare right side under a radical after completing the square.", axes={"a":[1,2,3,6,7,9,10,11,13,15,17,18]})
    a("completing-square-leading-coefficient/kp1", "Solve $2x^2+12x-{a}=0$ by dividing through first and completing the square. Report the roots as (smaller, larger).", "(-3-sqrt(a/2+9),-3+sqrt(a/2+9))", "Divide all coefficients by $2$: $x^2+6x={a}/2$. Add $9$ to obtain $(x+3)^2={a}/2+9$, then take both roots and subtract $3$.", "Divide every term by the leading coefficient before completing the square.", axes={"a":[2*(n*n-9) for n in range(4,16)]})
    a("completing-square-leading-coefficient/kp2", "Solve $2x^2+4x-{a}=0$ by completing the square. Report exact roots as (smaller, larger).", "(-1-sqrt(4+2*a)/2,-1+sqrt(4+2*a)/2)", r"After dividing, $x^2+2x={a}/2$. Adding $1$ gives $(x+1)^2=({a}+2)/2$; write its square root as $\sqrt{{4+2({a})}}/2$ and subtract $1$.", "Retain exact fractions after dividing by the leading coefficient.", axes={"a":[1,3,5,9,11,13,15,17,19,21,27,29]})
    a("completing-square-leading-coefficient/kp3", "Solve $x^2+3x-{a}=0$ by completing the square. Report exact roots as (smaller, larger).", "((-3-sqrt(9+4*a))/2,(-3+sqrt(9+4*a))/2)", "Add $(3/2)^2=9/4$ after moving ${a}$: $(x+3/2)^2={a}+9/4$. Take both roots and subtract $3/2$.", "Half an odd coefficient is a fraction; square it exactly.", axes={"a":[1,3,5,6,7,8,11,12,13,14,15,16]})


def formula(a):
    a("applying-the-quadratic-formula/kp1", "Rewrite $2x^2+{a}=3x$ with zero on the right. Report its quadratic-formula coefficients as (a, b, c).", "multipart(2,-3,a)", "Move $3x$ left: $2x^2-3x+{a}=0$. Read coefficients in descending powers, keeping the minus sign on the linear term.", "Identify the coefficients only after rearranging into standard form.")
    a("applying-the-quadratic-formula/kp2", "Use the quadratic formula to solve $x^2+4x-{a}=0$. Report the roots as (smaller, larger).", "(-2-sqrt(4+a),-2+sqrt(4+a))", r"The discriminant is $4^2-4(1)(-{a})=16+4({a})$. Insert it in $(-4\pm\sqrt{{16+4({a})}})/2$ and reduce.", "Compute the discriminant first, then divide the entire numerator by twice the leading coefficient.", axes={"a":[n*n-4 for n in range(3,15)]})
    a("applying-the-quadratic-formula/kp3", "Use the quadratic formula on $4x^2+4x-{a}=0$. Report reduced roots as (smaller, larger).", "((-1-sqrt(1+a))/2,(-1+sqrt(1+a))/2)", r"The discriminant is $16+16({a})$. Evaluate $(-4\pm\sqrt{{16+16({a})}})/8$; extract a factor $4$ from the radical and reduce both fractions.", "Simplify each numerator with the whole denominator after taking the square root.", axes={"a":[n*n-1 for n in range(2,26,2)]})
    a("quadratic-formula/kp1", "Solve $x^2+2x-{a}=0$ with the quadratic formula. Report fully simplified exact roots as (smaller, larger).", "(-1-sqrt(a+1),-1+sqrt(a+1))", r"The discriminant $4+4({a})$ has square factor $4$. Its radical is $2\sqrt{{{a}+1}}$; cancel $2$ against the formula's denominator.", "Extract the perfect-square factor from the discriminant before reducing.", axes={"a":[1,2,4,5,6,9,10,12,13,14,16,18]})
    a("quadratic-formula/kp2", "Solve $2x^2+2x-{a}=0$ with the quadratic formula. Report fully reduced exact roots as (smaller, larger).", "((-1-sqrt(1+2*a))/2,(-1+sqrt(1+2*a))/2)", "The discriminant is $4(1+2({a}))$. Extract its factor $4$ and cancel a factor $2$ from both numerator terms and denominator $4$.", "Cancel a common factor from the entire numerator, not from only one term.", axes={"a":[1,2,3,5,6,7,8,9,10,11,14,15]})
    a("quadratic-formula/kp3", "How many real solutions does $2x^2+4x+{a}=0$ have? Decide using the quadratic formula's discriminant.", "0", "The discriminant is $16-8({a})$. Every allowed constant exceeds $2$, making it negative, so the quadratic formula yields no real roots.", "Check whether the discriminant admits a real square root before calculating roots.", axes={"a":range(3,15)})
