#!/usr/bin/env python3
"""Explicit, hand-verified 4th exemplars for six named `arithmetic-core` KPs.

Unlike the generic `same_shape_new_operands` family (which redraws EVERY
bare integer operand independently and picks a family-generic solution
sketch from the operator alone), every recipe here is written for ONE named
knowledge point, encodes THAT knowledge point's own authored constraint
literally (a digit count, "ends in zero", "nonzero remainder"), and carries
a solution sketch specific to that constraint — never the generic
sign-counting sketch a coarse operator-only classifier would attach to a
knowledge point that holds no negative number at all.

`test_apply_arithmetic_core_recipes.py` is the semantic table: one row per
knowledge point below, naming its own constraint and checking every new
exemplar against it independently (not by re-running this module's own
arithmetic, which would be circular, but by recomputing divmod/product from
the parsed problem text itself).

Default is a dry run: reports what it would change and writes nothing. Pass
`--write` to edit `curriculum/foundations/00-arithmetic-core.yaml` in place.
"""
from __future__ import annotations

from foundations_curriculum_patch import (
    ExemplarKey,
    KpKey,
    NewExemplar,
)
from foundations_recipe_cli import run_recipe_cli

UNIT_FILE = "curriculum/foundations/00-arithmetic-core.yaml"

QR_CONTRACT = "quotient_remainder"


def _qr_sketch(dividend_text: str, dividend: int, divisor: int) -> str:
    quotient, remainder = divmod(dividend, divisor)
    product = divisor * quotient
    return f"${divisor} \\times {quotient} = {product}$, remainder ${dividend_text} - {product} = {remainder}$."


#: Eight practice exemplars in the safe integration base lack a
#: `solution_sketch`. Four were authored without one; four powers-of-ten
#: sketches were removed when the coarse generic generator was rolled back.
#: — found by inspection, not generated by the coarse family classifier.
#: Every sketch here names only that exemplar's own already-served problem
#: and answer, the same convention `apply_foundations_solution_sketches.py`
#: uses for the pure-numeric family.
MISSING_SKETCHES: dict[ExemplarKey, str] = {
    ExemplarKey("multiplying-by-powers-of-ten", "kp1", 0):
        'Multiplying by 10 appends one zero to 47: $47 \\times 10 = 470$.',
    ExemplarKey("multiplying-by-powers-of-ten", "kp1", 1):
        'Multiplying by 100 appends two zeros to 36: $36 \\times 100 = 3600$.',
    ExemplarKey("multiplying-by-powers-of-ten", "kp1", 2):
        'Multiplying by 1000 appends three zeros to 8: $8 \\times 1000 = 8000$.',
    ExemplarKey("multiplying-by-powers-of-ten", "kp2", 1):
        'Strip one trailing zero from each factor: $24 \\times 3 = 72$; append two zeros: $7200$.',
    ExemplarKey("division-with-remainders", "kp1", 1): _qr_sketch("26", 26, 4),
    ExemplarKey("division-with-remainders", "kp2", 1): _qr_sketch("50", 50, 6),
    ExemplarKey("long-division", "kp3", 1): _qr_sketch("1{,}000", 1000, 24),
    ExemplarKey("long-division-one-digit", "kp3", 0): _qr_sketch("725", 725, 3),
}


def _qr(dividend: int, divisor: int, suffix: str) -> NewExemplar:
    quotient, remainder = divmod(dividend, divisor)
    problem = f"Compute ${dividend} \\div {divisor}${suffix}"
    answer = f"{quotient} R{remainder}"
    sketch = (
        f"${divisor} \\times {quotient} = {divisor * quotient}$, "
        f"remainder ${dividend} - {divisor * quotient} = {remainder}$."
    )
    contract = f'{{"kind":"quotient_remainder","divisor":{divisor}}}'
    return NewExemplar(problem, answer, sketch, with_contract=True, contract_override=contract)


_ZERO_WORDS = {1: "one", 2: "two", 3: "three"}


def _power_of_ten(factor: int, power: int) -> NewExemplar:
    zeros = len(str(power)) - 1
    product = factor * power
    problem = f"Compute ${factor} \\times {power}$."
    word = _ZERO_WORDS.get(zeros, str(zeros))
    # No false intermediate equality: `factor * power` is never `factor`
    # itself, so the sketch never claims one.
    sketch = f"Multiplying by {power} appends {word} zero{'s' if zeros != 1 else ''} to {factor}: ${factor} \\times {power} = {product}$."
    return NewExemplar(problem, str(product), sketch, with_contract=True)


def _ends_in_zero_product(a: int, b: int) -> NewExemplar:
    da, db = a // 10, b // 10
    # `a // 10` and `b // 10` already strip ONE trailing zero from each
    # factor unconditionally, so the running count starts at 2, not 1 — a
    # caught defect: the original count started at 1 and so undercounted
    # every pair by exactly one zero.
    zeros = 2
    while da % 10 == 0:
        da //= 10
        zeros += 1
    while db % 10 == 0:
        db //= 10
        zeros += 1
    product = a * b
    problem = f"Compute ${a} \\times {b}$."
    word = _ZERO_WORDS.get(zeros, str(zeros))
    sketch = f"${da} \\times {db} = {da * db}$, then append the {word} zero{'s' if zeros != 1 else ''}: ${product}$."
    return NewExemplar(problem, str(product), sketch, with_contract=True)


RECIPES: dict[KpKey, list[NewExemplar]] = {
    # constraint: "2-digit dividend, 1-digit divisor, nonzero remainder"
    KpKey("division-with-remainders", "kp1"): [
        _qr(53, 6, ". Give quotient and remainder."),
        _qr(71, 9, ". Give quotient and remainder."),
    ],
    # constraint: "remainder strictly smaller than the divisor"
    KpKey("division-with-remainders", "kp2"): [
        _qr(44, 9, ". Give quotient and remainder."),
        _qr(61, 8, ". Give quotient and remainder."),
    ],
    # constraint: "2-digit divisor, nonzero remainder; answer as 'q Rr'"
    KpKey("long-division", "kp3"): [
        _qr(863, 45, ". Give quotient and remainder."),
        _qr(591, 47, ". Give quotient and remainder."),
    ],
    # constraint: "3-digit dividend, 1-digit divisor, nonzero remainder"
    KpKey("long-division-one-digit", "kp3"): [
        _qr(614, 9, ". Give quotient and remainder."),
        _qr(803, 6, ". Give quotient and remainder."),
    ],
    # constraint: "1-2 digit number times 10, 100, or 1000"
    KpKey("multiplying-by-powers-of-ten", "kp1"): [
        _power_of_ten(12, 1000),
    ],
    # constraint: "both factors end in zeros; underlying fact from the tables"
    KpKey("multiplying-by-powers-of-ten", "kp2"): [
        _ends_in_zero_product(90, 40),
    ],
}


def main() -> int:
    return run_recipe_cli(
        UNIT_FILE,MISSING_SKETCHES,RECIPES,
        lambda _sketched,applied,count,verb:
            f"{applied} knowledge point(s), {count} new exemplar(s) {verb}",
        sketch_summary=lambda count,verb:f"{count} missing solution_sketch line(s) {verb}",
        sketch_refusal="REFUSED (solution sketches)",
        recipe_refusal="REFUSED (new exemplars)",
        description=__doc__,
    )


if __name__ == "__main__":
    raise SystemExit(main())
