"""Audit-clean symbolic recipe data for unit 05."""
DATA = {'additions': {('compound-inequalities', 'kp1'): [{'answer': '-2 <= x < 4',
                                                   'contract': None,
                                                   'contract_override': None,
                                                   'problem': 'Solve $-3 \\le 2x + 1 < 9$.',
                                                   'solution_sketch': 'Subtract $1$: $-4 \\le 2x < 8$; divide by $2$.',
                                                   'with_contract': False},
                                                  {'answer': '2 < x <= 5',
                                                   'contract': None,
                                                   'contract_override': None,
                                                   'problem': 'Solve $5 < 3x - 1 \\le 14$.',
                                                   'solution_sketch': 'Add $1$: $6 < 3x \\le 15$; divide by $3$.',
                                                   'with_contract': False}],
               ('graphing-inequalities-number-line', 'kp1'): [{'answer': 'closed',
                                                               'contract': '{"kind":"label","options":[["closed"],["open"]]}',
                                                               'contract_override': None,
                                                               'problem': 'To graph $x \\le 5$, is the circle at $5$ '
                                                                          'open or closed?',
                                                               'solution_sketch': '$\\le$ is inclusive, so the circle '
                                                                                  'is closed.',
                                                               'with_contract': False},
                                                              {'answer': 'open',
                                                               'contract': '{"kind":"label","options":[["closed"],["open"]]}',
                                                               'contract_override': None,
                                                               'problem': 'To graph $x > -4$, is the circle at $-4$ '
                                                                          'open or closed?',
                                                               'solution_sketch': '$>$ is strict, so the circle is '
                                                                                  'open.',
                                                               'with_contract': False}],
               ('graphing-inequalities-number-line', 'kp3'): [{'answer': 'x >= 2',
                                                               'contract': None,
                                                               'contract_override': None,
                                                               'problem': 'A number line shows a closed circle at $2$ '
                                                                          'with a ray to the right. Write the '
                                                                          'inequality.',
                                                               'solution_sketch': 'A closed circle is inclusive; right '
                                                                                  'means greater than or equal.',
                                                               'with_contract': False},
                                                              {'answer': 'x < -5',
                                                               'contract': None,
                                                               'contract_override': None,
                                                               'problem': 'A number line shows an open circle at $-5$ '
                                                                          'with a ray to the left. Write the '
                                                                          'inequality.',
                                                               'solution_sketch': 'An open circle is strict; left '
                                                                                  'means less than.',
                                                               'with_contract': False}],
               ('graphing-linear-inequalities', 'kp1'): [{'answer': 'dashed',
                                                          'contract': '{"kind":"label","options":[["dashed"],["solid"]]}',
                                                          'contract_override': None,
                                                          'problem': 'For $y < 3x - 2$, is the boundary line solid or '
                                                                     'dashed?',
                                                          'solution_sketch': 'Strict inequality ($<$) $\\to$ dashed.',
                                                          'with_contract': False},
                                                         {'answer': 'solid',
                                                          'contract': '{"kind":"label","options":[["dashed"],["solid"]]}',
                                                          'contract_override': None,
                                                          'problem': 'For $y \\ge -2x + 1$, is the boundary line solid '
                                                                     'or dashed?',
                                                          'solution_sketch': 'Inclusive inequality ($\\ge$) $\\to$ '
                                                                             'solid.',
                                                          'with_contract': False}],
               ('graphing-linear-inequalities', 'kp2'): [{'answer': 'yes',
                                                          'contract': '{"kind":"label","options":[["yes"],["no"]]}',
                                                          'contract_override': None,
                                                          'problem': 'Is $(1, 1)$ a solution of $y < 2x + 3$?',
                                                          'solution_sketch': '$1 < 2 + 3 = 5$ is true.',
                                                          'with_contract': False},
                                                         {'answer': 'yes',
                                                          'contract': '{"kind":"label","options":[["yes"],["no"]]}',
                                                          'contract_override': None,
                                                          'problem': 'Is $(0, -1)$ a solution of $y \\ge x - 4$?',
                                                          'solution_sketch': '$-1 \\ge -4$ is true.',
                                                          'with_contract': False}],
               ('interval-notation', 'kp2'): [{'answer': 'x <= 3',
                                               'contract': '{"kind":"inequality_union"}',
                                               'contract_override': None,
                                               'problem': 'Write $(-\\infty, 3]$ as an inequality.',
                                               'solution_sketch': 'The ray extends left and includes $3$.',
                                               'with_contract': False}],
               ('interval-notation', 'kp3'): [{'answer': '(-∞, -5] ∪ (4, ∞)',
                                               'contract': '{"kind":"inequality_union"}',
                                               'contract_override': None,
                                               'problem': 'Solve $x + 1 \\le -4$ or $2x - 3 > 5$ and give the answer '
                                                          'in interval notation.',
                                               'solution_sketch': '$x \\le -5$ or $x > 4$, so $(-\\infty,-5] \\cup '
                                                                  '(4,\\infty)$.',
                                               'with_contract': False}],
               ('solutions-of-inequalities', 'kp1'): [{'answer': 'true',
                                                       'contract': '{"kind":"label","options":[["true"],["false"]]}',
                                                       'contract_override': None,
                                                       'problem': 'Is the statement $-7 < -2$ true or false?',
                                                       'solution_sketch': '$-7$ is to the left of $-2$ on the number '
                                                                          'line.',
                                                       'with_contract': False},
                                                      {'answer': 'false',
                                                       'contract': '{"kind":"label","options":[["true"],["false"]]}',
                                                       'contract_override': None,
                                                       'problem': 'True or false: $6 \\ge 9$?',
                                                       'solution_sketch': '$6$ is less than $9$.',
                                                       'with_contract': False}],
               ('substitution-with-isolated-variable', 'kp2'): [{'answer': '(5, 11)',
                                                                 'contract': '{"kind":"exact"}',
                                                                 'contract_override': None,
                                                                 'problem': 'Solve the system $y = 2x + 1$, $y = x + '
                                                                            '6$.',
                                                                 'solution_sketch': '$2x + 1 = x + 6$; $x = 5$; $y = '
                                                                                    '11$.',
                                                                 'with_contract': False},
                                                                {'answer': '(3, 12)',
                                                                 'contract': '{"kind":"exact"}',
                                                                 'contract_override': None,
                                                                 'problem': 'Solve the system $y = 4x$, $y = x + 9$.',
                                                                 'solution_sketch': '$4x = x + 9$; $3x = 9$; $x = 3$; '
                                                                                    '$y = 12$.',
                                                                 'with_contract': False}],
               ('writing-inequalities-from-statements', 'kp1'): [{'answer': 'x <= 20',
                                                                  'contract': None,
                                                                  'contract_override': None,
                                                                  'problem': 'Write an inequality: "$x$ is at most '
                                                                             '$20$".',
                                                                  'solution_sketch': '"At most" means $\\le$.',
                                                                  'with_contract': False},
                                                                 {'answer': 'n > 5',
                                                                  'contract': None,
                                                                  'contract_override': None,
                                                                  'problem': 'Write an inequality for the number of '
                                                                             'items $n$: "more than $5$ items".',
                                                                  'solution_sketch': '"More than" is strict: $n > 5$.',
                                                                  'with_contract': False}],
               ('writing-inequalities-from-statements', 'kp3'): [{'answer': '50',
                                                                  'contract': None,
                                                                  'contract_override': None,
                                                                  'problem': 'You need at least $50$ points to '
                                                                             'qualify. What is the fewest points that '
                                                                             'works?',
                                                                  'solution_sketch': 'The fewest value meeting $n \\ge '
                                                                                     '50$ is $50$ itself.',
                                                                  'with_contract': False},
                                                                 {'answer': 'w <= 40',
                                                                  'contract': None,
                                                                  'contract_override': None,
                                                                  'problem': 'A crate holds at most $40$ kg. Write the '
                                                                             'inequality for the weight $w$.',
                                                                  'solution_sketch': '"At most" means $\\le$.',
                                                                  'with_contract': False}]},
 'contracts': {('graphing-inequalities-number-line', 'kp1', 0): '{"kind":"label","options":[["closed"],["open"]]}',
               ('graphing-inequalities-number-line', 'kp1', 1): '{"kind":"label","options":[["closed"],["open"]]}',
               ('graphing-linear-inequalities', 'kp1', 0): '{"kind":"label","options":[["dashed"],["solid"]]}',
               ('graphing-linear-inequalities', 'kp1', 1): '{"kind":"label","options":[["dashed"],["solid"]]}',
               ('interval-notation', 'kp2', 0): '{"kind":"inequality_union"}',
               ('interval-notation', 'kp2', 1): '{"kind":"inequality_union"}',
               ('interval-notation', 'kp2', 2): '{"kind":"inequality_union"}',
               ('interval-notation', 'kp3', 0): '{"kind":"inequality_union"}',
               ('interval-notation', 'kp3', 1): '{"kind":"inequality_union"}',
               ('interval-notation', 'kp3', 2): '{"kind":"inequality_union"}'},
 'patches': {('interval-notation', 'kp2', 0): {'answer': None,
                                               'answer_contract': '{"kind":"inequality_union"}',
                                               'problem': None,
                                               'solution_sketch': None},
             ('interval-notation', 'kp2', 1): {'answer': None,
                                               'answer_contract': '{"kind":"inequality_union"}',
                                               'problem': None,
                                               'solution_sketch': None},
             ('interval-notation', 'kp2', 2): {'answer': None,
                                               'answer_contract': '{"kind":"inequality_union"}',
                                               'problem': None,
                                               'solution_sketch': None},
             ('interval-notation', 'kp2', 3): {'answer': None,
                                               'answer_contract': '{"kind":"inequality_union"}',
                                               'problem': None,
                                               'solution_sketch': None},
             ('interval-notation', 'kp3', 0): {'answer': None,
                                               'answer_contract': '{"kind":"inequality_union"}',
                                               'problem': None,
                                               'solution_sketch': None},
             ('interval-notation', 'kp3', 1): {'answer': None,
                                               'answer_contract': '{"kind":"inequality_union"}',
                                               'problem': None,
                                               'solution_sketch': None},
             ('interval-notation', 'kp3', 2): {'answer': None,
                                               'answer_contract': '{"kind":"inequality_union"}',
                                               'problem': None,
                                               'solution_sketch': None},
             ('interval-notation', 'kp3', 3): {'answer': None,
                                               'answer_contract': '{"kind":"inequality_union"}',
                                               'problem': None,
                                               'solution_sketch': None}},
 'path': 'curriculum/foundations/05-systems-inequalities.yaml',
 'sketches': {('compound-inequalities', 'kp1', 1): 'Subtract $1$: $2 < 2x \\le 10$; divide by $2$.',
              ('graphing-inequalities-number-line', 'kp1', 0): '$\\ge$ is inclusive, so the circle is closed.',
              ('graphing-inequalities-number-line', 'kp1', 1): '$<$ is strict, so the circle is open.',
              ('graphing-inequalities-number-line', 'kp3', 0): 'A closed circle is inclusive; left means less than or '
                                                               'equal.',
              ('graphing-inequalities-number-line', 'kp3', 1): 'An open circle is strict; right means greater than.',
              ('graphing-linear-inequalities', 'kp1', 1): 'Inclusive inequality ($\\le$) $\\to$ solid.',
              ('interval-notation', 'kp2', 1): 'Every value at or below $-1$; the round bracket at $-\\infty$ never '
                                               'closes, and the square bracket at $-1$ includes it.',
              ('interval-notation', 'kp2', 2): 'A square bracket at $4$ becomes $\\ge$; the ray extends right without '
                                               'bound.',
              ('interval-notation', 'kp3', 2): 'The interval $(-\\infty, 1)$ is $x < 1$; $[5, \\infty)$ is $x \\ge 5$.',
              ('solutions-of-inequalities', 'kp1', 1): '$4 \\ge 4$ holds with equality.',
              ('writing-inequalities-from-statements', 'kp1', 0): '"At least" means $\\ge$.',
              ('writing-inequalities-from-statements', 'kp1', 1): '"Fewer than" is strict: $n < 8$.',
              ('writing-inequalities-from-statements', 'kp3', 0): 'The fewest value meeting $n \\ge 30$ is $30$ '
                                                                  'itself.',
              ('writing-inequalities-from-statements', 'kp3', 1): '"At most" means $\\le$.'}}
