"""Audit-clean symbolic recipe data for unit 03."""
DATA = {'additions': {('checking-a-solution', 'kp1'): [{'answer': 'yes',
                                                 'contract': '{"kind":"label","options":[["yes"],["no"]]}',
                                                 'contract_override': None,
                                                 'problem': 'Is $t = -3$ a solution of $5t + 2 = -13$? Answer yes or '
                                                            'no.',
                                                 'solution_sketch': '$5(-3) + 2 = -13$.',
                                                 'with_contract': False}],
               ('consecutive-integer-problems', 'kp1'): [{'answer': '7',
                                                          'contract': None,
                                                          'contract_override': None,
                                                          'problem': 'Five less than four times a number is $23$. Find '
                                                                     'the number.',
                                                          'solution_sketch': '$4x - 5 = 23$; $4x = 28$; $x = 7$.',
                                                          'with_contract': False},
                                                         {'answer': '8',
                                                          'contract': None,
                                                          'contract_override': None,
                                                          'problem': 'The sum of a number and three times the number '
                                                                     'is $32$. Find the number.',
                                                          'solution_sketch': '$x + 3x = 32$; $4x = 32$; $x = 8$.',
                                                          'with_contract': False}],
               ('equation-word-problems', 'kp1'): [{'answer': '45',
                                                    'contract': '{"kind":"exact"}',
                                                    'contract_override': None,
                                                    'problem': 'Two clubs have $60$ members combined; the chess club '
                                                               'has three times as many members as the debate club. '
                                                               'How many are in the chess club?',
                                                    'solution_sketch': 'Debate $x$, chess $3x$: $4x = 60$; $x = 15$; '
                                                                       'chess has $45$.',
                                                    'with_contract': False},
                                                   {'answer': '17',
                                                    'contract': '{"kind":"exact"}',
                                                    'contract_override': None,
                                                    'problem': 'A $40$ m rope is cut into two pieces; one piece is $6$ '
                                                               'm longer than the other. How long is the shorter '
                                                               'piece?',
                                                    'solution_sketch': '$x + (x + 6) = 40$; $2x = 34$; $x = 17$.',
                                                    'with_contract': False}],
               ('equation-word-problems', 'kp3'): [{'answer': '17',
                                                    'contract': '{"kind":"exact"}',
                                                    'contract_override': None,
                                                    'problem': 'Nora is $6$ years older than Omar, and the sum of '
                                                               'their ages is $28$. How old is Nora?',
                                                    'solution_sketch': 'Omar $x$, Nora $x + 6$: $2x + 6 = 28$; $x = '
                                                                       '11$; Nora is $17$.',
                                                    'with_contract': False},
                                                   {'answer': '10',
                                                    'contract': '{"kind":"exact"}',
                                                    'contract_override': None,
                                                    'problem': 'A father is $5$ times as old as his son. In $10$ years '
                                                               'he will be $3$ times as old as his son. How old is the '
                                                               'son now?',
                                                    'solution_sketch': '$5s + 10 = 3(s + 10)$; $5s + 10 = 3s + 30$; $s '
                                                                       '= 10$.',
                                                    'with_contract': False}],
               ('literal-equations', 'kp1'): [{'answer': 'x = (r - q)/p',
                                               'contract': '{"kind":"exact"}',
                                               'contract_override': None,
                                               'problem': 'Solve $px + q = r$ for $x$.',
                                               'solution_sketch': 'Subtract $q$, then divide by $p$.',
                                               'with_contract': False},
                                              {'answer': 'B = 3V/h',
                                               'contract': '{"kind":"exact"}',
                                               'contract_override': None,
                                               'problem': 'Solve $V = \\frac{1}{3}Bh$ for $B$.',
                                               'solution_sketch': 'Multiply by $3$, divide by $h$.',
                                               'with_contract': False}],
               ('literal-equations', 'kp2'): [{'answer': 'x = k/(m - n)',
                                               'contract': '{"kind":"exact"}',
                                               'contract_override': None,
                                               'problem': 'Solve $mx - nx = k$ for $x$.',
                                               'solution_sketch': 'Factor: $x(m - n) = k$; divide by $(m - n)$.',
                                               'with_contract': False},
                                              {'answer': 'x = 3y - 5',
                                               'contract': '{"kind":"exact"}',
                                               'contract_override': None,
                                               'problem': 'Solve $y = \\frac{x + 5}{3}$ for $x$.',
                                               'solution_sketch': '$3y = x + 5$; $x = 3y - 5$.',
                                               'with_contract': False}],
               ('literal-equations', 'kp3'): [{'answer': 'b = P/2 - a',
                                               'contract': '{"kind":"exact"}',
                                               'contract_override': None,
                                               'problem': 'Solve $P = 2(a + b)$ for $b$.',
                                               'solution_sketch': 'Divide by $2$: $\\frac{P}{2} = a + b$; subtract '
                                                                  '$a$.',
                                               'with_contract': False},
                                              {'answer': 'm = 2T/k - n',
                                               'contract': '{"kind":"exact"}',
                                               'contract_override': None,
                                               'problem': 'Solve $T = \\frac{1}{2}k(m + n)$ for $m$.',
                                               'solution_sketch': 'Multiply by $2$: $2T = k(m + n)$; divide by $k$; '
                                                                  'subtract $n$.',
                                               'with_contract': False}],
               ('parts-of-an-expression', 'kp1'): [{'answer': '3',
                                                    'contract': None,
                                                    'contract_override': None,
                                                    'problem': 'How many terms does $5x - 3y + 8$ have?',
                                                    'solution_sketch': 'Terms are separated by $+$ and $-$: $5x$, '
                                                                       '$-3y$, $8$.',
                                                    'with_contract': False}],
               ('rearranging-formulas', 'kp1'): [{'answer': 'q = p + r',
                                                  'contract': '{"kind":"exact"}',
                                                  'contract_override': None,
                                                  'problem': 'Solve $p = q - r$ for $q$.',
                                                  'solution_sketch': 'Add $r$ to both sides.',
                                                  'with_contract': False},
                                                 {'answer': 'h = A/b',
                                                  'contract': '{"kind":"exact"}',
                                                  'contract_override': None,
                                                  'problem': 'Solve $A = bh$ for $h$.',
                                                  'solution_sketch': 'Divide both sides by $b$.',
                                                  'with_contract': False}],
               ('rearranging-formulas', 'kp2'): [{'answer': 'w = V/(l*h)',
                                                  'contract': '{"kind":"exact"}',
                                                  'contract_override': None,
                                                  'problem': 'Solve $V = lwh$ for $w$ (treat $l$ and $h$ as known).',
                                                  'solution_sketch': 'Divide both sides by $l$ and by $h$.',
                                                  'with_contract': False},
                                                 {'answer': 'x = (y - b)/m',
                                                  'contract': '{"kind":"exact"}',
                                                  'contract_override': None,
                                                  'problem': 'Solve $y = mx + b$ for $x$ (treat $m$ and $b$ as known).',
                                                  'solution_sketch': 'Subtract $b$, then divide by $m$.',
                                                  'with_contract': False}],
               ('substituting-values', 'kp1'): [{'answer': '19',
                                                 'contract': None,
                                                 'contract_override': None,
                                                 'problem': 'Evaluate $4x - 5$ when $x = 6$.',
                                                 'solution_sketch': '$4(6) - 5 = 19$.',
                                                 'with_contract': False}],
               ('translating-phrases-to-expressions', 'kp1'): [{'answer': 'm + 9',
                                                                'contract': None,
                                                                'contract_override': None,
                                                                'problem': 'Write an expression: $9$ more than a '
                                                                           'number $m$.',
                                                                'solution_sketch': '"$9$ more than" adds: $m + 9$.',
                                                                'with_contract': False},
                                                               {'answer': 'y - 6',
                                                                'contract': None,
                                                                'contract_override': None,
                                                                'problem': 'Write an expression: the difference of a '
                                                                           'number $y$ and $6$.',
                                                                'solution_sketch': 'The difference subtracts in the '
                                                                                   'stated order: $y - 6$.',
                                                                'with_contract': False}],
               ('translating-phrases-to-expressions', 'kp2'): [{'answer': '8v',
                                                                'contract': None,
                                                                'contract_override': None,
                                                                'problem': 'Write an expression: the product of $8$ '
                                                                           'and $v$.',
                                                                'solution_sketch': 'Product means multiply: $8v$.',
                                                                'with_contract': False},
                                                               {'answer': 'z/9',
                                                                'contract': None,
                                                                'contract_override': None,
                                                                'problem': 'Write an expression: the quotient of $z$ '
                                                                           'and $9$.',
                                                                'solution_sketch': 'Quotient means divide: $z/9$.',
                                                                'with_contract': False}],
               ('translating-phrases-to-expressions', 'kp3'): [{'answer': '3m - 5',
                                                                'contract': None,
                                                                'contract_override': None,
                                                                'problem': 'Write an expression: $5$ less than three '
                                                                           'times a number $m$.',
                                                                'solution_sketch': '"$5$ less than" reverses the '
                                                                                   'order: start with $3m$, subtract '
                                                                                   '$5$.',
                                                                'with_contract': False},
                                                               {'answer': '6w + 7',
                                                                'contract': None,
                                                                'contract_override': None,
                                                                'problem': 'Write an expression: $7$ more than the '
                                                                           'product of $6$ and $w$.',
                                                                'solution_sketch': 'The product $6w$ comes first, then '
                                                                                   'add $7$.',
                                                                'with_contract': False}],
               ('translating-sentences-to-equations', 'kp1'): [{'answer': '23',
                                                                'contract': None,
                                                                'contract_override': None,
                                                                'problem': 'A number decreased by $9$ is $14$. Find '
                                                                           'the number.',
                                                                'solution_sketch': '$x - 9 = 14$; $x = 23$.',
                                                                'with_contract': False},
                                                               {'answer': '7',
                                                                'contract': None,
                                                                'contract_override': None,
                                                                'problem': 'Three times a number plus $8$ is $29$. '
                                                                           'Find the number.',
                                                                'solution_sketch': '$3x + 8 = 29$; $3x = 21$; $x = 7$.',
                                                                'with_contract': False}],
               ('writing-expressions-from-patterns', 'kp2'): [{'answer': '3h + 5',
                                                               'contract': None,
                                                               'contract_override': None,
                                                               'problem': 'A parking garage charges €5 to enter plus '
                                                                          '€3 per hour. Write an expression for the '
                                                                          'total cost after $h$ hours.',
                                                               'solution_sketch': 'The rate $3$ per hour is the '
                                                                                  'coefficient; the flat $5$ is added '
                                                                                  'once.',
                                                               'with_contract': False},
                                                              {'answer': '3n + 1',
                                                               'contract': None,
                                                               'contract_override': None,
                                                               'problem': 'A fence post pattern uses $4$ posts for $1$ '
                                                                          'section, $7$ for $2$, $10$ for $3$, adding '
                                                                          '$3$ per section. Write an expression for '
                                                                          'the posts in $n$ sections.',
                                                               'solution_sketch': 'Step $3$ per section; $3(1) + 1 = '
                                                                                  '4$ checks.',
                                                               'with_contract': False}]},
 'contracts': {},
 'patches': {},
 'path': 'curriculum/foundations/03-expressions-equations.yaml',
 'sketches': {('parts-of-an-expression', 'kp1', 2): 'The constant term has no variable factor: $-8$.',
              ('rearranging-formulas', 'kp1', 0): 'Subtract $b$ from both sides: $x = y - b$.',
              ('substituting-values', 'kp1', 1): '$2(10) - 7 = 13$.',
              ('substituting-values', 'kp1', 2): '$10 - 2(3) = 4$.',
              ('translating-phrases-to-expressions', 'kp1', 0): '"$7$ more than" adds: $n + 7$.',
              ('translating-phrases-to-expressions', 'kp1', 1): 'The difference subtracts in the stated order: $x - '
                                                                '4$.',
              ('translating-phrases-to-expressions', 'kp2', 0): 'Product means multiply: $6w$.',
              ('translating-phrases-to-expressions', 'kp2', 1): 'Quotient means divide: $y/5$.',
              ('translating-phrases-to-expressions', 'kp3', 1): 'The product $4t$ comes first, then add $5$.',
              ('writing-expressions-from-patterns', 'kp2', 0): 'Fixed €20 plus €8 per month: $8m + 20$.'}}
