//! FIX-M6-G, finding F17. The oracle of the SPA route table.
//!
//! `web/src/api/types.ts` holds `ROUTES`, a hand-written mirror of the routes
//! that [`cadus_web::create_app`] mounts. Before this file, nothing read
//! `create_app` on the way to that mirror: a route added to the service and not
//! copied into `ROUTES` failed no check in either tree.
//!
//! This file is the missing reader. It dumps every route of the live router to
//! the committed fixture `web/src/api/routes.generated.json`, and it fails when
//! the fixture and the router disagree. `web/test/api-contract.test.ts` reads
//! the same fixture, so the TypeScript table now has a source outside itself.
//!
//! # How the dump reads the router
//!
//! axum 0.8 publishes no iterator over the routes of a `Router`, so the dump
//! takes two steps and each one covers the blind spot of the other:
//!
//! 1. **The path list comes from the crate source.** Every `.route("..."` string
//!    literal under `crates/web/src` is a candidate path. A new route is a new
//!    literal, so the candidate list grows with the service.
//! 2. **The methods come from the live router.** The dump sends one request per
//!    candidate with the method `CADUSPROBE`, which no route serves. A mounted
//!    path answers `405` and carries the `Allow` header that axum builds from
//!    the mounted methods; an unmounted path answers `404` from the fallback.
//!    The probe therefore reaches NO handler and needs NO database.
//!
//! A route the source names and `create_app` does not mount fails
//! [`every_route_string_of_the_source_is_mounted`], so step 1 never reports a
//! path that the service lacks.
//!
//! # Regenerating the fixture
//!
//! ```sh
//! CADUS_ROUTES_BLESS=1 cargo test -p cadus-web --test route_table
//! ```
//!
//! `scripts/gate.sh` regenerates the fixture into a scratch copy and compares
//! the bytes, so a committed fixture that the router no longer matches fails the
//! gate as well as the test.
//!
//! Every expected value below is a literal of this file or of the committed
//! fixture. The probe method, the two fallback status codes, and the two `Allow`
//! values are written out.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

use axum::Router;
use axum::body::Body;
use axum::http::{Method, Request, StatusCode};
use cadus_store::{DEFAULT_CLIENT_TIMEOUT_MS, Db};
use cadus_web::{AppState, create_app};
use serde::{Deserialize, Serialize};
use sqlx::postgres::PgPoolOptions;
use tower::ServiceExt;

/// The environment variable that turns the check into a rewrite.
const BLESS_VAR: &str = "CADUS_ROUTES_BLESS";

/// The probe method. No route of `create_app` serves it, so the request reaches
/// the method fallback of a mounted path and the not-found fallback of an
/// unmounted one. It reaches no handler at all.
const PROBE_METHOD: &str = "CADUSPROBE";

/// The value that fills a `{param}` segment of a route template.
const PROBE_SEGMENT: &str = "probe";

/// The fixture, relative to the repository root.
const FIXTURE_REL: &str = "web/src/api/routes.generated.json";

/// The `note` field of the fixture, written out.
const FIXTURE_NOTE: &str = "Generated by crates/web/tests/route_table.rs from the live create_app \
                            router. Do not edit by hand: regenerate with CADUS_ROUTES_BLESS=1 \
                            cargo test -p cadus-web --test route_table";

/// The method names the dump accepts in an `Allow` header.
///
/// `HEAD` is dropped from every row: axum mounts it with `get`, and the SPA
/// never issues one. A route mounted with any OTHER method fails the run, so a
/// `put` route or a `delete` route reaches the fixture format on purpose and
/// never by accident.
const KNOWN_METHODS: [&str; 3] = ["GET", "HEAD", "POST"];

/// One row of the dump.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
struct RouteRow {
    /// The HTTP method, upper case.
    method: String,
    /// The axum route template, `{param}` and all.
    path: String,
}

/// The whole fixture.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
struct Fixture {
    /// Why the file exists and how to rewrite it.
    note: String,
    /// Every mounted route, sorted by path and then by method.
    routes: Vec<RouteRow>,
}

/// The repository root. Cargo runs a test with the PACKAGE directory as its
/// working directory, so the path comes from the manifest directory instead.
fn repo_root() -> PathBuf {
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    manifest
        .parent()
        .and_then(Path::parent)
        .expect("crates/web sits two levels under the repository root")
        .to_path_buf()
}

/// An application on a lazy pool that points at an address with no server.
///
/// The probe carries no credential, and `crates/web/src/auth/layer.rs` states
/// that a request with no credential costs no query, so the pool never connects.
fn offline_app() -> Router {
    let pool = PgPoolOptions::new()
        .connect_lazy("postgresql://nobody@127.0.0.1:1/nodb")
        .expect("a lazy pool needs no server");
    create_app(AppState::new(Db::new(pool, DEFAULT_CLIENT_TIMEOUT_MS)))
}

/// Collect every `.rs` file under `dir`.
fn collect_rs(dir: &Path, out: &mut Vec<PathBuf>) {
    for entry in fs::read_dir(dir).expect("the source directory reads") {
        let path = entry.expect("the directory entry reads").path();
        if path.is_dir() {
            collect_rs(&path, out);
        } else if path.extension().is_some_and(|ext| ext == "rs") {
            out.push(path);
        }
    }
}

/// Every route template that the crate source names.
///
/// The scan takes the first string literal of each `.route(` call. rustfmt is
/// free to put that literal on the next line, so the text after the marker is
/// trimmed before the quote is read.
fn route_templates() -> BTreeSet<String> {
    let src = repo_root().join("crates/web/src");
    let mut files = Vec::new();
    collect_rs(&src, &mut files);
    let mut templates = BTreeSet::new();
    for file in files {
        let text = fs::read_to_string(&file).expect("a source file reads");
        for tail in text.split(".route(").skip(1) {
            let Some(body) = tail.trim_start().strip_prefix('"') else {
                continue;
            };
            let Some(end) = body.find('"') else {
                continue;
            };
            templates.insert(body[..end].to_string());
        }
    }
    templates
}

/// Turn a route template into a path that a request carries.
fn concrete_path(template: &str) -> String {
    let mut out = String::new();
    for segment in template.split('/').skip(1) {
        out.push('/');
        if segment.starts_with('{') && segment.ends_with('}') {
            out.push_str(PROBE_SEGMENT);
        } else {
            out.push_str(segment);
        }
    }
    out
}

/// Send one probe. Give back the status and the `Allow` header.
async fn probe(app: &Router, template: &str) -> (StatusCode, Option<String>) {
    let request = Request::builder()
        .method(Method::from_bytes(PROBE_METHOD.as_bytes()).expect("the probe method is a token"))
        .uri(concrete_path(template))
        .body(Body::empty())
        .expect("the probe request builds");
    let response = app
        .clone()
        .oneshot(request)
        .await
        .expect("the router answers every request");
    let status = response.status();
    let allow = response.headers().get("allow").map(|value| {
        value
            .to_str()
            .expect("the Allow header is ASCII")
            .to_string()
    });
    (status, allow)
}

/// Dump every mounted route of `create_app`, sorted.
async fn dump_routes() -> Vec<RouteRow> {
    let app = offline_app();
    let mut rows = Vec::new();
    for template in route_templates() {
        let (status, allow) = probe(&app, &template).await;
        assert_eq!(
            status,
            StatusCode::METHOD_NOT_ALLOWED,
            "the source names {template}, and create_app does not mount it"
        );
        let allow = allow.unwrap_or_else(|| panic!("{template} answered 405 with no Allow header"));
        for name in allow.split(',').map(str::trim) {
            assert!(
                KNOWN_METHODS.contains(&name),
                "{template} allows {name}; extend KNOWN_METHODS and the fixture format"
            );
            if name == "HEAD" {
                continue;
            }
            rows.push(RouteRow {
                method: name.to_string(),
                path: template.clone(),
            });
        }
    }
    rows.sort();
    rows
}

/// Test 1 (finding F17). The committed fixture is the live router.
///
/// The TypeScript table had no check of this kind. This one reads
/// `create_app`, and it fails when the two disagree. Add a route to `create_app`
/// and this test is red until the fixture is regenerated. The regenerated
/// fixture then turns `web/test/api-contract.test.ts` red until `ROUTES` names
/// the new row too.
#[tokio::test]
async fn the_fixture_is_the_route_table_of_create_app() {
    let routes = dump_routes().await;
    let built = Fixture {
        note: FIXTURE_NOTE.to_string(),
        routes,
    };
    let mut rendered = serde_json::to_string_pretty(&built).expect("the dump serializes");
    rendered.push('\n');

    let path = repo_root().join(FIXTURE_REL);
    if std::env::var_os(BLESS_VAR).is_some() {
        fs::write(&path, &rendered).expect("the fixture writes");
        return;
    }

    let committed = fs::read_to_string(&path).unwrap_or_else(|error| {
        panic!("{FIXTURE_REL} does not read ({error}); rewrite it with {BLESS_VAR}=1")
    });

    // The rows come first. A whole-file comparison of a 35-route fixture prints
    // two walls of JSON and names no route, so the row list gives the reader the
    // one line that changed.
    let parsed: Fixture = serde_json::from_str(&committed)
        .unwrap_or_else(|error| panic!("{FIXTURE_REL} is not the fixture format ({error})"));
    assert_eq!(
        parsed.routes, built.routes,
        "{FIXTURE_REL} is not the route table of create_app; rewrite it with {BLESS_VAR}=1 cargo \
         test -p cadus-web --test route_table"
    );

    // The bytes come second. They cover the `note` and the layout, so a hand
    // edit of either one fails too.
    assert_eq!(
        parsed.note, built.note,
        "{FIXTURE_REL} carries another note; rewrite it with {BLESS_VAR}=1"
    );
    assert_eq!(
        committed, rendered,
        "{FIXTURE_REL} holds the right routes in another layout; rewrite it with {BLESS_VAR}=1"
    );
}

/// Test 2. The probe finds the difference between a mounted path and an
/// unmatched path.
///
/// Every value here is a literal. Without this test, an axum release that
/// stopped setting `Allow`, or a fallback that answered `404` to every method,
/// would empty the dump, and the fixture would be rewritten to an empty list
/// with no failure in between.
#[tokio::test]
async fn the_probe_separates_a_mounted_path_from_an_unmatched_path() {
    let app = offline_app();

    let (status, allow) = probe(&app, "/api/health").await;
    assert_eq!(status, StatusCode::METHOD_NOT_ALLOWED);
    assert_eq!(allow.as_deref(), Some("GET,HEAD"));

    let (status, allow) = probe(&app, "/api/enroll").await;
    assert_eq!(status, StatusCode::METHOD_NOT_ALLOWED);
    assert_eq!(allow.as_deref(), Some("POST"));

    let (status, allow) = probe(&app, "/api/task/{task_id}/answer").await;
    assert_eq!(status, StatusCode::METHOD_NOT_ALLOWED);
    assert_eq!(allow.as_deref(), Some("POST"));

    let (status, allow) = probe(&app, "/api/no-such-path").await;
    assert_eq!(status, StatusCode::NOT_FOUND);
    assert_eq!(allow, None);
}

/// Test 3. The source scan finds routes, and `create_app` mounts every one.
///
/// The scan is the path half of the dump. An empty scan makes the fixture an
/// empty list, and a route string that no router merges makes the fixture claim
/// a path the service does not serve. The two literals below stop the empty
/// scan. The loop states the rule that the panic message of `dump_routes`
/// names.
#[tokio::test]
async fn every_route_string_of_the_source_is_mounted() {
    let templates = route_templates();
    assert!(
        templates.contains("/api/health"),
        "the source scan lost /api/health"
    );
    assert!(
        templates.contains("/api/admin/content/{digest}/reject"),
        "the source scan lost the reject route"
    );

    let app = offline_app();
    let mut unmounted = Vec::new();
    for template in &templates {
        let (status, _) = probe(&app, template).await;
        if status == StatusCode::NOT_FOUND {
            unmounted.push(template.clone());
        }
    }
    assert_eq!(unmounted, Vec::<String>::new());
}
